import { useEffect,useMemo,useState } from 'react'
import { Alert,Button,Card,Collapse,Empty,Image,InputNumber,message,Modal,Progress,Segmented,Select,Slider,Space,Statistic,Switch,Table,Tag,Typography,Upload } from 'antd'
import { CheckCircleFilled,DownloadOutlined,ExportOutlined,FileSearchOutlined,FireOutlined,FolderOpenOutlined,PlayCircleOutlined,ReloadOutlined,RocketOutlined,ScissorOutlined,UploadOutlined,VideoCameraOutlined } from '@ant-design/icons'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { api,Drama,FactoryAnalysis,FactoryJob,FactoryOutputMode,GeneratedAsset,HookAsset,ScriptSegment } from '../api'

const clock=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));const hours=Math.floor(value/3600);const minutes=Math.floor((value%3600)/60);const rest=value%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`}
const size=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:bytes>=1024**2?`${(bytes/1024**2).toFixed(1)} MB`:`${Math.round(bytes/1024)} KB`
const imageExtensions=new Set(['jpg','jpeg','png','webp'])
const statusColor:Record<string,string>={queued:'default',processing:'blue',completed:'green',failed:'red'}
const statusLabel:Record<string,string>={queued:'排队中',processing:'加工中',completed:'已完成',failed:'失败'}
const assetLabels:Record<GeneratedAsset['kind'],{text:string;color:string}>={clean_full:{text:'完整净化版',color:'green'},hook_full:{text:'高能片头版',color:'blue'},meta_episode:{text:'Meta 单集',color:'gold'}}
const reviewLabel:Record<string,{text:string;color:string}>={pending:{text:'待复核',color:'gold'},approved:{text:'已采用',color:'green'},rejected:{text:'已排除',color:'default'}}
const sensitiveReviewLabel:Record<string,{text:string;color:string}>={pending:{text:'默认移除',color:'gold'},approved:{text:'已标记移除',color:'red'},rejected:{text:'已保留',color:'green'}}
const riskScoreLabel:Record<string,string>={body_focus:'人体聚焦',action:'动作',dialogue_context:'语境',expression_audio:'表情氛围',scene_context:'场景'}

export default function ContentFactory(){
  const[params]=useSearchParams();const navigate=useNavigate()
  const[dramas,setDramas]=useState<Drama[]>([]);const[dramaId,setDramaId]=useState<number>();const[analysis,setAnalysis]=useState<FactoryAnalysis>()
  const[jobs,setJobs]=useState<FactoryJob[]>([]);const[assets,setAssets]=useState<GeneratedAsset[]>([]);const[hooks,setHooks]=useState<HookAsset[]>([])
  const[busy,setBusy]=useState(false);const[tab,setTab]=useState<'analysis'|'process'|'hooks'>('analysis');const[hookScope,setHookScope]=useState<'current'|'all'>('current')
  const[uploadOpen,setUploadOpen]=useState(false);const[sourceFiles,setSourceFiles]=useState<File[]>([]);const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({});const[uploadStartedAt,setUploadStartedAt]=useState<number>()
  const[outputModes,setOutputModes]=useState<FactoryOutputMode[]>(['clean_full','hook_variants']);const[hookDuration,setHookDuration]=useState(15);const[hooksPerVariant,setHooksPerVariant]=useState(1);const[variantCount,setVariantCount]=useState(3)
  const[profile,setProfile]=useState<'balanced'|'small'>('balanced');const[removeSensitive,setRemoveSensitive]=useState(true);const[selectedHooks,setSelectedHooks]=useState<number[]>([])
  const[msg,holder]=message.useMessage();const drama=dramas.find(x=>x.id===dramaId);const latestJob=jobs[0];const processing=jobs.some(x=>['queued','processing'].includes(x.status));const analysisPending=['queued','processing'].includes(analysis?.status??'');const analyzing=analysisPending&&analysis?.is_active!==false;const analysisInterrupted=analysisPending&&analysis?.is_active===false

  const reloadDramas=async(preferred=dramaId)=>{const items=await api.list();setDramas(items);const requested=Number(params.get('drama'));setDramaId(items.some(x=>x.id===preferred)?preferred:items.some(x=>x.id===requested)?requested:items[0]?.id)}
  const loadFactory=async(id:number)=>{const[a,j,g,h]=await Promise.all([api.factoryAnalysis(id),api.factoryJobs(id),api.factoryAssets(id),api.factoryHooks()]);setAnalysis(a);setJobs(j);setAssets(g);setHooks(h)}
  useEffect(()=>{reloadDramas(undefined).catch(e=>msg.error(e.message))},[])
  useEffect(()=>{if(!dramaId){setAnalysis(undefined);setJobs([]);setAssets([]);return}loadFactory(dramaId).catch(e=>msg.error(e.message))},[dramaId])
  useEffect(()=>{if(!dramaId||(!processing&&!analyzing))return;const timer=window.setInterval(()=>{loadFactory(dramaId).then(()=>reloadDramas(dramaId)).catch(()=>undefined)},2500);return()=>window.clearInterval(timer)},[dramaId,processing,analyzing])

  const analyze=async()=>{if(!dramaId)return;setBusy(true);try{const result=await api.analyzeFactory(dramaId);setAnalysis(result);msg.success('识别任务已开始，可留在本页查看进度')}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const adopt=async(episode:string,segment:ScriptSegment)=>{if(!drama)return;const duplicate=drama.highlights.some(x=>x.episode===episode&&Math.abs(x.start-segment.start)<.1);if(duplicate)return msg.info('该高能点已在库中');try{await api.reviewFactoryAnalysis(drama.id,{episode,kind:'high_energy',start:segment.start,end:segment.end,decision:'approved'});const updated=await api.highlights(drama.id,[...drama.highlights,{episode,start:segment.start,end:segment.end,note:segment.energy_reasons.join('；')||segment.text.slice(0,60)}]);setDramas(items=>items.map(x=>x.id===updated.id?updated:x));await api.syncFactoryHooks(drama.id);await loadFactory(drama.id);msg.success('已加入高能库')}catch(e){msg.error((e as Error).message)}}
  const reviewCandidate=async(episode:string,kind:'high_energy'|'sensitive',segment:ScriptSegment,decision:'approved'|'rejected')=>{if(!dramaId)return;try{setAnalysis(await api.reviewFactoryAnalysis(dramaId,{episode,kind,start:segment.start,end:segment.end,decision}));if(kind==='high_energy'&&decision==='approved')await api.syncFactoryHooks(dramaId);msg.success(kind==='sensitive'?(decision==='approved'?'已标记为移除，生成净化版时自动删除':'已标记为保留'):(decision==='approved'?'已采用该片段':'已排除该片段'))}catch(e){msg.error((e as Error).message)}}
  const uploadSources=async()=>{if(!drama||!sourceFiles.length)return;setBusy(true);setUploadStartedAt(Date.now());try{const ordered=[...sourceFiles].sort((a,b)=>{const ai=imageExtensions.has(a.name.split('.').pop()?.toLowerCase()||'');const bi=imageExtensions.has(b.name.split('.').pop()?.toLowerCase()||'');return Number(ai)-Number(bi)||a.name.localeCompare(b.name,undefined,{numeric:true})});for(const file of ordered){const ext=file.name.split('.').pop()?.toLowerCase()||'';const key=file.webkitRelativePath||file.name;await api.uploadVideo(drama.title,'内容工厂本地原片',file,value=>setUploadProgress(old=>({...old,[key]:value})),imageExtensions.has(ext)?'stills':'episodes')}msg.success(`已导入 ${sourceFiles.length} 个文件`);setUploadOpen(false);setSourceFiles([]);setUploadProgress({});setUploadStartedAt(undefined);await reloadDramas(drama.id);await loadFactory(drama.id)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const toggleMode=(mode:FactoryOutputMode)=>setOutputModes(current=>current.includes(mode)?current.filter(x=>x!==mode):[...current,mode])
  const startProcessing=async()=>{if(!dramaId)return;if(!outputModes.length)return msg.warning('至少选择一种产出流程');if(removeSensitive&&outputModes.some(x=>x!=='meta_split')&&analysis?.status!=='completed')return msg.warning('请先完成敏感内容识别');setBusy(true);try{const job=await api.startFactoryProcessing(dramaId,{max_duration_seconds:180,hook_duration_seconds:hookDuration,publish_variant_count:variantCount,remove_sensitive:removeSensitive,compression_profile:profile,output_modes:outputModes,hooks_per_variant:hooksPerVariant,hook_ids:selectedHooks});setJobs(old=>[job,...old]);setTab('process');msg.success(`加工任务 #${job.id} 已开始`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const toggleHook=async(row:HookAsset,active:boolean)=>{try{const changed=await api.setFactoryHookActive(row.id,active);setHooks(items=>items.map(x=>x.id===changed.id?changed:x))}catch(e){msg.error((e as Error).message)}}
  const refreshHookMetrics=async()=>{if(!dramaId)return;setBusy(true);try{const result=await api.collectMetrics(true);await loadFactory(dramaId);msg.success(`平台数据已刷新 ${result.created+result.updated} 条`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const handoffToJianying=(row:GeneratedAsset)=>{const link=document.createElement('a');link.href=`/api/factory/assets/${row.id}/download`;link.download=row.filename;document.body.appendChild(link);link.click();link.remove();window.open('https://www.jianying.com/','_blank','noopener,noreferrer');msg.success('成品已开始下载')}

  const highEnergy=useMemo(()=>analysis?.episodes.flatMap(ep=>ep.high_energy.map(row=>({episode:ep.episode,...row})))??[],[analysis]);const sensitive=useMemo(()=>analysis?.episodes.flatMap(ep=>ep.sensitive.map(row=>({episode:ep.episode,...row})))??[],[analysis]);const analysisReady=analysis?.status==='completed'&&!analysis.requires_reanalysis;const pendingSensitive=sensitive.filter(row=>row.review_status==='pending').length
  const uploadStats=useMemo(()=>{const total=sourceFiles.reduce((sum,file)=>sum+file.size,0);const uploaded=sourceFiles.reduce((sum,file)=>sum+file.size*(uploadProgress[file.webkitRelativePath||file.name]??0)/100,0);const percent=total?Math.round(uploaded/total*100):0;const seconds=uploadStartedAt?Math.max(1,(Date.now()-uploadStartedAt)/1000):0;const speed=seconds?uploaded/seconds:0;return{total,uploaded,percent,speed,eta:speed?Math.max(0,(total-uploaded)/speed):0}},[sourceFiles,uploadProgress,uploadStartedAt])
  const visibleHooks=useMemo(()=>hooks.filter(x=>hookScope==='all'||x.drama_id===dramaId),[hooks,hookScope,dramaId]);const activeHooks=hooks.filter(x=>x.active);const metaForecast=analysisReady?analysis.episodes.reduce((sum,ep)=>sum+Math.ceil(ep.duration/180),0):undefined
  const segmentColumns=[{title:'时间',width:115,render:(_:unknown,row:ScriptSegment)=>`${clock(row.start)}–${clock(row.end)}`},{title:'脚本',dataIndex:'text'},{title:'高能',width:90,render:(_:unknown,row:ScriptSegment)=>row.high_energy?<Tag color="orange">{row.energy_score.toFixed(1)}</Tag>:'—'},{title:'敏感内容',width:210,render:(_:unknown,row:ScriptSegment)=>Object.entries(row.sensitive).length?Object.entries(row.sensitive).map(([kind,words])=><Tag color="red" key={kind}>{kind} · {words.join('、')}</Tag>):'—'}]

  return <div className="workspace-page factory-page">{holder}
    <div className="page-heading page-heading-rich"><Typography.Title level={2}>内容工厂</Typography.Title><Space wrap><Select showSearch optionFilterProp="label" placeholder="选择剧目任务" value={dramaId} onChange={id=>{setDramaId(id);setSelectedHooks([])}} options={dramas.map(x=>({value:x.id,label:x.title}))} style={{width:240}}/><Button icon={<FolderOpenOutlined/>} disabled={!drama} onClick={()=>{setUploadStartedAt(undefined);setUploadOpen(true)}}>导入源文件</Button><Button type="primary" icon={<FileSearchOutlined/>} loading={busy||analyzing} disabled={!drama?.episode_count||analyzing} onClick={analyze}>{analyzing?'AI 识别中':analysisInterrupted?'继续识别':analysisReady?'重新识别':'识别整部剧'}</Button></Space></div>
    {drama&&<div className="factory-task-strip"><b>{drama.title}</b><span>源文件 {drama.episode_count}</span><span>登记集数 {drama.total_episode_count}</span><span>已生成 {drama.generated_files.length}</span>{drama.genres.map(genre=><Tag key={genre}>{genre}</Tag>)}</div>}
    <Segmented block className="overview-pager factory-pager" value={tab} onChange={value=>setTab(value as typeof tab)} options={[{value:'analysis',label:'1 内容识别'},{value:'process',label:'2 产出流程'},{value:'hooks',label:'3 高能库'}]}/>

    {tab==='analysis'&&<div className="factory-inner">{!drama?<Card><Empty description="请先在剧库建立剧目任务"><Button href="/dramas" type="primary">前往剧库</Button></Empty></Card>:!drama.episode_count?<Card className="factory-empty"><Empty description="尚未导入源文件"><Button type="primary" icon={<UploadOutlined/>} onClick={()=>setUploadOpen(true)}>选择本地文件夹</Button></Empty></Card>:analyzing?<Card className="factory-analysis-progress" title="AI 正在识别整部剧"><Progress percent={analysis?.progress??0} status="active"/><b>{analysis?.current_step||'准备本地转写与抽帧'}</b><div className="factory-analysis-live"><span>已完成剧集 {analysis?.episodes.length??0}/{analysis?.episode_count??drama.episode_count}</span><span>已抽帧 {analysis?.sampled_frame_count??0}</span><span>模型调用 {analysis?.api_call_count??0}</span>{Boolean(analysis?.resume_count)&&<span>已自动续跑 {analysis?.resume_count} 次</span>}</div></Card>:analysisInterrupted?<Card className="factory-empty"><Alert type="warning" showIcon message="识别任务已暂停" description={`已保存 ${analysis?.episodes.length??0} 集结果，可以从断点继续。`}/><Button type="primary" onClick={analyze}>继续识别</Button></Card>:analysis?.status==='failed'?<Card className="factory-empty"><Alert type="error" showIcon message="内容识别中断" description={analysis.error_message}/><Button type="primary" onClick={analyze}>从断点继续</Button></Card>:!analysisReady?<Card className="factory-empty">{analysis?.ai_ready===false&&<Alert type="warning" showIcon message="尚未配置多模态模型" description="配置 GEMINI_API_KEY 或 QWEN_API_KEY 后即可结合脚本和抽帧识别。"/>}{analysis?.requires_reanalysis&&<Alert type="info" showIcon message="需要升级识别结果" description="已有结果只分析了对白和音量，请重新识别以加入真实画面判断。"/>}<Empty description="等待识别"><Button type="primary" loading={busy} onClick={analyze}>识别脚本、抽帧、高能点与敏感片段</Button></Empty></Card>:<>
      <div className="summary-strip factory-summary"><Statistic title="源文件" value={analysis.episode_count} suffix="集"/><Statistic title="总时长" value={clock(analysis.total_duration)}/><Statistic title="脚本片段" value={analysis.segment_count}/><Statistic title="证据抽帧" value={analysis.sampled_frame_count}/><Statistic title="高能点" value={analysis.high_energy_count} valueStyle={{color:'#d97706'}}/><Statistic title="敏感片段" value={analysis.sensitive_count} valueStyle={{color:analysis.sensitive_count?'#c2413b':undefined}}/></div>
      <div className="factory-analysis-meta"><Tag color="blue">{analysis.provider} · {analysis.model}</Tag><span>模型调用 {analysis.api_call_count} 次</span>{pendingSensitive>0&&<Tag color="gold">{pendingSensitive} 个低置信风险待复核</Tag>}</div>
      <Card title="逐集时间轴"><Collapse items={analysis.episodes.map(ep=>({key:ep.episode,label:<Space><b>{ep.episode}</b><Tag>{clock(ep.duration)}</Tag>{ep.high_energy.length>0&&<Tag color="orange">高能 {ep.high_energy.length}</Tag>}{ep.sensitive.length>0&&<Tag color="red">敏感 {ep.sensitive.length}</Tag>}</Space>,children:<Table size="small" rowKey={row=>`${ep.episode}-${row.start}`} dataSource={ep.segments} columns={segmentColumns} pagination={false} scroll={{x:760}}/>}))}/></Card>
      <div className="factory-review-grid"><Card title={<><FireOutlined/> 高能候选</>}><Table size="small" rowKey={row=>`${row.episode}-${row.start}`} dataSource={highEnergy} pagination={{pageSize:6}} columns={[{title:'剧集',dataIndex:'episode',width:100},{title:'时间',render:(_,row)=>`${clock(row.start)}–${clock(row.end)}`,width:115},{title:'AI 依据',render:(_,row)=><Space direction="vertical" size={2}><span>{row.energy_reasons.join('；')||row.text}</span><Space size={4}><Tag color="orange">评分 {row.energy_score.toFixed(0)}</Tag><Tag color={reviewLabel[row.review_status??'pending'].color}>{reviewLabel[row.review_status??'pending'].text}</Tag></Space></Space>},{title:'证据帧',width:125,render:(_,row)=><Image.PreviewGroup>{(row.frame_files??[]).slice(0,2).map(file=><Image key={file} width={48} height={34} src={api.factoryFrameUrl(drama.id,file)} style={{objectFit:'cover',borderRadius:6}}/>)}</Image.PreviewGroup>},{title:'操作',width:130,render:(_,row)=><Space size={4}><Button size="small" type="primary" disabled={row.review_status==='approved'} onClick={()=>adopt(row.episode,row)}>采用</Button><Button size="small" disabled={row.review_status==='rejected'} onClick={()=>reviewCandidate(row.episode,'high_energy',row,'rejected')}>排除</Button></Space>}]} scroll={{x:830}}/></Card><Card title="敏感片段复核"><Table size="small" rowKey={row=>`${row.episode}-${row.start}`} dataSource={sensitive} pagination={{pageSize:6}} locale={{emptyText:'未识别到敏感片段'}} columns={[{title:'剧集',dataIndex:'episode',width:95},{title:'时间',render:(_,row)=>`${clock(row.start)}–${clock(row.end)}`,width:110},{title:'AI 风险',render:(_,row)=><Space direction="vertical" size={2}>{Object.entries(row.sensitive).map(([kind,words])=><span key={kind}><Tag color="red">{kind}</Tag>{words.join('、')}</span>)}{row.risk_scores&&<Space size={[2,2]} wrap>{Object.entries(row.risk_scores).filter(([,score])=>(score??0)>0).map(([key,score])=><Tag key={key}>{riskScoreLabel[key]??key} {score}</Tag>)}</Space>}<Space size={4}><Tag color={(row.overall_risk_score??0)>=60?'red':(row.overall_risk_score??0)>=30?'gold':'default'}>风险 {row.overall_risk_score??Math.round((row.confidence??0)*100)}</Tag><Tag color={sensitiveReviewLabel[row.review_status??'pending'].color}>{sensitiveReviewLabel[row.review_status??'pending'].text}</Tag></Space></Space>},{title:'证据帧',width:125,render:(_,row)=><Image.PreviewGroup>{(row.frame_files??[]).slice(0,2).map(file=><Image key={file} width={48} height={34} src={api.factoryFrameUrl(drama.id,file)} style={{objectFit:'cover',borderRadius:6}}/>)}</Image.PreviewGroup>},{title:'操作',width:130,render:(_,row)=><Space size={4}><Button size="small" danger disabled={row.review_status==='approved'} onClick={()=>reviewCandidate(row.episode,'sensitive',row,'approved')}>移除</Button><Button size="small" disabled={row.review_status==='rejected'} onClick={()=>reviewCandidate(row.episode,'sensitive',row,'rejected')}>保留</Button></Space>}]} scroll={{x:900}}/></Card></div>
    </>}</div>}

    {tab==='process'&&<div className="factory-inner">
      <Card title="选择产出方式"><div className="factory-output-grid">
        <button type="button" className={`factory-output-card ${outputModes.includes('clean_full')?'is-selected':''}`} onClick={()=>toggleMode('clean_full')}><span className="factory-output-index">01</span><VideoCameraOutlined/><b>原剧合并净化</b><small>顺序拼接 · 敏感内容去除 · 完整视频</small>{outputModes.includes('clean_full')&&<CheckCircleFilled/>}</button>
        <button type="button" className={`factory-output-card ${outputModes.includes('hook_variants')?'is-selected':''}`} onClick={()=>toggleMode('hook_variants')}><span className="factory-output-index">02</span><FireOutlined/><b>高能片头批量版</b><small>1–3个片头 · 多版本 · 完整视频</small>{outputModes.includes('hook_variants')&&<CheckCircleFilled/>}</button>
        <button type="button" className={`factory-output-card ${outputModes.includes('meta_split')?'is-selected':''}`} onClick={()=>toggleMode('meta_split')}><span className="factory-output-index">03</span><ScissorOutlined/><b>Meta 逐集切分</b><small>不拼接 · 单集≤3分钟 · 自动均分</small>{outputModes.includes('meta_split')&&<CheckCircleFilled/>}</button>
      </div></Card>
      <div className="factory-process-grid"><Card title="加工参数" className="factory-parameter-card">
        <div className={`factory-parameter-layout ${outputModes.includes('hook_variants')?'':'is-single'}`}>
          <section className="factory-parameter-section"><div className="factory-parameter-title"><span>01</span><b>基础设置</b></div><div className="factory-setting-stack">
            <label className="factory-setting-row"><span>压缩档位</span><Select value={profile} onChange={setProfile} options={[{value:'balanced',label:'均衡 · CRF 23'},{value:'small',label:'省空间 · CRF 28'}]}/></label>
            {outputModes.some(x=>x!=='meta_split')&&<label className="factory-setting-row"><span>敏感内容去除</span><Switch checked={removeSensitive} onChange={setRemoveSensitive}/></label>}
            {outputModes.includes('meta_split')&&<label className="factory-setting-row"><span>Meta 单集上限</span><strong>180 秒</strong></label>}
          </div></section>
          {outputModes.includes('hook_variants')&&<section className="factory-parameter-section is-hook"><div className="factory-parameter-title"><span>02</span><b>高能版本</b></div>
            <div className="factory-duration-card"><div><span>片头时长</span><strong>{hookDuration} 秒</strong></div><Slider min={15} max={30} step={1} value={hookDuration} marks={{15:'15s',30:'30s'}} tooltip={{formatter:value=>`${value} 秒`}} onChange={setHookDuration}/></div>
            <div className="factory-compact-options"><label><span>每版高能点</span><InputNumber min={1} max={3} value={hooksPerVariant} addonAfter="个" onChange={value=>setHooksPerVariant(value??1)}/></label><label><span>批量版本</span><InputNumber min={1} max={50} value={variantCount} addonAfter="版" onChange={value=>setVariantCount(value??1)}/></label></div>
            <label className="factory-hook-source"><span>高能点来源</span><Select mode="multiple" allowClear value={selectedHooks} onChange={setSelectedHooks} placeholder="自动按评分选择，或手动指定" options={activeHooks.map(x=>({value:x.id,label:`#${x.id} ${x.drama_title} · ${x.episode} ${clock(x.start)}`}))}/></label>
          </section>}
        </div>
        <div className="factory-parameter-footer"><div className="factory-forecast"><div><span>完整净化版</span><strong>{outputModes.includes('clean_full')?1:0}</strong><small>个文件</small></div><div><span>高能片头版</span><strong>{outputModes.includes('hook_variants')?variantCount:0}</strong><small>个文件</small></div><div><span>Meta 单集</span><strong>{outputModes.includes('meta_split')?(metaForecast??'—'):0}</strong><small>个文件</small></div></div><Button size="large" type="primary" icon={<PlayCircleOutlined/>} loading={busy} disabled={!drama?.episode_count||processing||!outputModes.length} onClick={startProcessing}>{processing?'加工中':'开始生成所选成品'}</Button></div>
      </Card>
        <Card title="当前任务" extra={<Button size="small" icon={<ReloadOutlined/>} disabled={!dramaId} onClick={()=>dramaId&&loadFactory(dramaId)}>刷新</Button>}>{latestJob?<><Space wrap><Tag color={statusColor[latestJob.status]}>{statusLabel[latestJob.status]||latestJob.status}</Tag><b>#{latestJob.id}</b><span>{latestJob.current_step}</span></Space><Progress percent={latestJob.progress} status={latestJob.status==='failed'?'exception':latestJob.status==='completed'?'success':'active'}/><div className="factory-job-stats"><span>净化版 {latestJob.clean_count}</span><span>高能版 {latestJob.publish_count}</span><span>Meta 单集 {latestJob.meta_count}</span><span>移除 {clock(latestJob.removed_seconds)}</span><span>输出 {size(latestJob.output_bytes)}</span></div>{latestJob.warnings.map(x=><Alert key={x} type="warning" showIcon message={x}/>)}{latestJob.error_message&&<Alert type="error" showIcon message={latestJob.error_message}/>}</>:<Empty description="暂无加工任务"/>}</Card></div>
      <Card title="已生成"><Table rowKey="id" dataSource={assets} pagination={{pageSize:12}} locale={{emptyText:'任务完成后自动进入剧库“已生成”'}} columns={[{title:'类型',width:125,render:(_,row)=>{const item=assetLabels[row.kind];return <Tag color={item.color}>{item.text}</Tag>}},{title:'文件名',dataIndex:'filename',ellipsis:true},{title:'时长',width:105,render:(_,row)=>clock(row.duration)},{title:'大小',width:100,render:(_,row)=>size(row.size_bytes)},{title:'高能点',width:140,render:(_,row)=>row.hook_asset_ids?.length?row.hook_asset_ids.map(id=>`#${id}`).join(' + '):row.hook_asset_id?`#${row.hook_asset_id}`:'—'},{title:'操作',width:330,render:(_,row)=><Space wrap><Button size="small" icon={<DownloadOutlined/>} href={`/api/factory/assets/${row.id}/download`} target="_blank">下载</Button>{row.kind!=='meta_episode'&&<Button size="small" icon={<ExportOutlined/>} onClick={()=>handoffToJianying(row)}>剪映</Button>}{row.clip_id&&<Button size="small" type="primary" icon={<RocketOutlined/>} onClick={()=>navigate(`/publishing?drama=${row.drama_id}`)}>发布</Button>}{row.kind==='meta_episode'&&<Button size="small" type="primary" onClick={()=>navigate(`/meta-delivery?drama=${row.drama_id}`)}>Meta 投递</Button>}</Space>}]} scroll={{x:980}}/></Card>
    </div>}

    {tab==='hooks'&&<div className="factory-inner"><div className="module-toolbar"><Segmented value={hookScope} onChange={v=>setHookScope(v as typeof hookScope)} options={[{value:'current',label:'当前剧目'},{value:'all',label:'全部剧目'}]}/><Space><Button icon={<ReloadOutlined/>} disabled={!dramaId} onClick={async()=>{if(dramaId)await api.syncFactoryHooks(dramaId);if(dramaId)await loadFactory(dramaId)}}>同步高能点</Button><Button type="primary" loading={busy} disabled={!dramaId} onClick={refreshHookMetrics}>刷新平台表现</Button></Space></div><Card className="table-card"><Table rowKey="id" dataSource={visibleHooks} pagination={{pageSize:12}} columns={[{title:'排名',width:70,render:(_,__,index)=>index+1},{title:'高能点',render:(_,row)=><Space direction="vertical" size={0}><b>#{row.id} · {row.drama_title}</b><Typography.Text type="secondary">{row.episode} · {clock(row.start)}–{clock(row.end)}</Typography.Text></Space>},{title:'依据',dataIndex:'note',ellipsis:true},{title:'热度',width:105,render:(_,row)=><b>{row.heat_score.toLocaleString()}</b>},{title:'发布表现',width:180,render:(_,row)=><Space size={4} wrap><Tag>播放 {row.views.toLocaleString()}</Tag><Tag>赞 {row.likes.toLocaleString()}</Tag><Tag>评 {row.comments.toLocaleString()}</Tag></Space>},{title:'复用',width:80,dataIndex:'use_count'},{title:'状态',width:90,render:(_,row)=><Switch size="small" checked={row.active} onChange={value=>toggleHook(row,value)}/>},{title:'预览',width:80,render:(_,row)=>row.preview_ready?<Button size="small" href={`/api/factory/hooks/${row.id}/video`} target="_blank">查看</Button>:'待生成'}]} scroll={{x:1000}}/></Card></div>}

    <Modal title={`导入源文件 · ${drama?.title??''}`} open={uploadOpen} onCancel={()=>!busy&&setUploadOpen(false)} footer={null} width={680} destroyOnHidden><Upload.Dragger directory multiple beforeUpload={()=>false} fileList={sourceFiles.map((file,index)=>({uid:`${index}-${file.name}`,name:file.webkitRelativePath||file.name,status:'done',originFileObj:file as any}))} onChange={({fileList})=>setSourceFiles(fileList.map(x=>x.originFileObj).filter(Boolean) as File[])} accept=".mp4,.mov,.mkv,.webm,.srt,.vtt,.jpg,.jpeg,.png,.webp"><p className="ant-upload-drag-icon"><FolderOpenOutlined/></p><p className="ant-upload-text">选择包含多集源文件的本地文件夹</p></Upload.Dragger>{sourceFiles.length>0&&<div className="factory-upload-summary"><div><b>总进度 {uploadStats.percent}%</b><span>{size(uploadStats.uploaded)} / {size(uploadStats.total)}{uploadStats.speed>0&&` · ${size(uploadStats.speed)}/s · 剩余约 ${clock(uploadStats.eta)}`}</span></div><Progress percent={uploadStats.percent} showInfo={false}/></div>}{sourceFiles.map(file=>{const key=file.webkitRelativePath||file.name;return <div key={key} className="upload-file"><span>{key}</span><Progress percent={uploadProgress[key]??0}/></div>})}<Button block size="large" type="primary" loading={busy} disabled={!sourceFiles.length} onClick={uploadSources}>按文件名顺序导入 {sourceFiles.length||''}</Button></Modal>
  </div>
}
