import { useEffect,useMemo,useState } from 'react'
import { Alert,Button,Card,Collapse,Empty,InputNumber,message,Modal,Progress,Segmented,Select,Space,Statistic,Switch,Table,Tag,Typography,Upload } from 'antd'
import { DownloadOutlined,FileSearchOutlined,FireOutlined,FolderOpenOutlined,PlayCircleOutlined,ReloadOutlined,RocketOutlined,UploadOutlined } from '@ant-design/icons'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { api,Drama,FactoryAnalysis,FactoryJob,GeneratedAsset,HookAsset,ScriptSegment } from '../api'

const clock=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));const hours=Math.floor(value/3600);const minutes=Math.floor((value%3600)/60);const rest=value%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`}
const size=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:bytes>=1024**2?`${(bytes/1024**2).toFixed(1)} MB`:`${Math.round(bytes/1024)} KB`
const imageExtensions=new Set(['jpg','jpeg','png','webp'])
const statusColor:Record<string,string>={queued:'default',processing:'blue',completed:'green',failed:'red'}

export default function ContentFactory(){
  const[params]=useSearchParams();const navigate=useNavigate()
  const[dramas,setDramas]=useState<Drama[]>([]);const[dramaId,setDramaId]=useState<number>();const[analysis,setAnalysis]=useState<FactoryAnalysis>()
  const[jobs,setJobs]=useState<FactoryJob[]>([]);const[assets,setAssets]=useState<GeneratedAsset[]>([]);const[hooks,setHooks]=useState<HookAsset[]>([])
  const[busy,setBusy]=useState(false);const[tab,setTab]=useState<'analysis'|'process'|'hooks'>('analysis');const[hookScope,setHookScope]=useState<'current'|'all'>('current')
  const[uploadOpen,setUploadOpen]=useState(false);const[sourceFiles,setSourceFiles]=useState<File[]>([]);const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({})
  const[hookDuration,setHookDuration]=useState(3);const[variantCount,setVariantCount]=useState(5);const[profile,setProfile]=useState<'balanced'|'small'>('balanced');const[removeSensitive,setRemoveSensitive]=useState(true);const[selectedHooks,setSelectedHooks]=useState<number[]>([])
  const[msg,holder]=message.useMessage();const drama=dramas.find(x=>x.id===dramaId);const latestJob=jobs[0];const processing=jobs.some(x=>['queued','processing'].includes(x.status))

  const reloadDramas=async(preferred=dramaId)=>{const items=await api.list();setDramas(items);const requested=Number(params.get('drama'));setDramaId(items.some(x=>x.id===preferred)?preferred:items.some(x=>x.id===requested)?requested:items[0]?.id)}
  const loadFactory=async(id:number)=>{const[a,j,g,h]=await Promise.all([api.factoryAnalysis(id),api.factoryJobs(id),api.factoryAssets(id),api.factoryHooks()]);setAnalysis(a);setJobs(j);setAssets(g);setHooks(h)}
  useEffect(()=>{reloadDramas(undefined).catch(e=>msg.error(e.message))},[])
  useEffect(()=>{if(!dramaId){setAnalysis(undefined);setJobs([]);setAssets([]);return}loadFactory(dramaId).catch(e=>msg.error(e.message))},[dramaId])
  useEffect(()=>{if(!dramaId||!processing)return;const timer=window.setInterval(()=>{loadFactory(dramaId).then(()=>reloadDramas(dramaId)).catch(()=>undefined)},2000);return()=>window.clearInterval(timer)},[dramaId,processing])

  const analyze=async()=>{if(!dramaId)return;setBusy(true);try{const result=await api.analyzeFactory(dramaId);setAnalysis(result);await api.syncFactoryHooks(dramaId);await loadFactory(dramaId);msg.success(`识别完成：${result.high_energy_count} 个高能点，${result.sensitive_count} 个敏感片段`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const adopt=async(episode:string,segment:ScriptSegment)=>{if(!drama)return;const duplicate=drama.highlights.some(x=>x.episode===episode&&Math.abs(x.start-segment.start)<.1);if(duplicate)return msg.info('该高能点已在库中');try{const updated=await api.highlights(drama.id,[...drama.highlights,{episode,start:segment.start,end:segment.end,note:segment.energy_reasons.join('；')||segment.text.slice(0,60)}]);setDramas(items=>items.map(x=>x.id===updated.id?updated:x));await api.syncFactoryHooks(drama.id);await loadFactory(drama.id);msg.success('已加入高能库')}catch(e){msg.error((e as Error).message)}}
  const uploadSources=async()=>{if(!drama||!sourceFiles.length)return;setBusy(true);try{const ordered=[...sourceFiles].sort((a,b)=>{const ai=imageExtensions.has(a.name.split('.').pop()?.toLowerCase()||'');const bi=imageExtensions.has(b.name.split('.').pop()?.toLowerCase()||'');return Number(ai)-Number(bi)||a.name.localeCompare(b.name,undefined,{numeric:true})});for(const file of ordered){const ext=file.name.split('.').pop()?.toLowerCase()||'';await api.uploadVideo(drama.title,'内容工厂本地原片',file,value=>setUploadProgress(old=>({...old,[file.name]:value})),imageExtensions.has(ext)?'stills':'episodes')}msg.success(`已导入 ${sourceFiles.length} 个文件`);setUploadOpen(false);setSourceFiles([]);setUploadProgress({});await reloadDramas(drama.id);await loadFactory(drama.id)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const startProcessing=async()=>{if(!dramaId)return;if(removeSensitive&&analysis?.status!=='completed')return msg.warning('请先完成脚本与敏感内容识别');setBusy(true);try{const job=await api.startFactoryProcessing(dramaId,{max_duration_seconds:180,hook_duration_seconds:hookDuration,publish_variant_count:variantCount,remove_sensitive:removeSensitive,compression_profile:profile,hook_ids:selectedHooks});setJobs(old=>[job,...old]);setTab('process');msg.success(`加工任务 #${job.id} 已开始`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const toggleHook=async(row:HookAsset,active:boolean)=>{try{const changed=await api.setFactoryHookActive(row.id,active);setHooks(items=>items.map(x=>x.id===changed.id?changed:x))}catch(e){msg.error((e as Error).message)}}
  const refreshHookMetrics=async()=>{if(!dramaId)return;setBusy(true);try{const result=await api.collectMetrics(true);await loadFactory(dramaId);msg.success(`平台数据已刷新 ${result.created+result.updated} 条`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}

  const highEnergy=useMemo(()=>analysis?.episodes.flatMap(ep=>ep.high_energy.map(row=>({episode:ep.episode,...row})))??[],[analysis]);const sensitive=useMemo(()=>analysis?.episodes.flatMap(ep=>ep.sensitive.map(row=>({episode:ep.episode,...row})))??[],[analysis]);const analysisReady=analysis?.status==='completed'
  const visibleHooks=useMemo(()=>hooks.filter(x=>hookScope==='all'||x.drama_id===dramaId),[hooks,hookScope,dramaId]);const activeHooks=hooks.filter(x=>x.active);const forecast=analysisReady?Math.ceil(analysis.total_duration/Math.max(60,180-hookDuration)):0
  const segmentColumns=[{title:'时间',width:115,render:(_:unknown,row:ScriptSegment)=>`${clock(row.start)}–${clock(row.end)}`},{title:'脚本',dataIndex:'text'},{title:'高能',width:90,render:(_:unknown,row:ScriptSegment)=>row.high_energy?<Tag color="orange">{row.energy_score.toFixed(1)}</Tag>:'—'},{title:'敏感内容',width:210,render:(_:unknown,row:ScriptSegment)=>Object.entries(row.sensitive).length?Object.entries(row.sensitive).map(([kind,words])=><Tag color="red" key={kind}>{kind} · {words.join('、')}</Tag>):'—'}]

  return <div className="workspace-page factory-page">{holder}
    <div className="page-heading page-heading-rich"><Typography.Title level={2}>内容工厂</Typography.Title><Space wrap><Select placeholder="选择剧目任务" value={dramaId} onChange={id=>{setDramaId(id);setSelectedHooks([])}} options={dramas.map(x=>({value:x.id,label:x.title}))} style={{width:240}}/><Button icon={<FolderOpenOutlined/>} disabled={!drama} onClick={()=>setUploadOpen(true)}>导入原片</Button><Button type="primary" icon={<FileSearchOutlined/>} loading={busy} disabled={!drama?.episode_count} onClick={analyze}>{analysisReady?'重新识别':'识别整部剧'}</Button></Space></div>
    {drama&&<div className="factory-task-strip"><b>{drama.title}</b><span>原片 {drama.episode_count}</span><span>全集 {drama.total_episode_count}</span><span>已生成 {drama.generated_files.length}</span>{drama.genres.map(genre=><Tag key={genre}>{genre}</Tag>)}</div>}
    <Segmented block className="overview-pager factory-pager" value={tab} onChange={value=>setTab(value as typeof tab)} options={[{value:'analysis',label:'1 脚本与敏感内容'},{value:'process',label:'2 拼接与成品'},{value:'hooks',label:'3 高能库'}]}/>

    {tab==='analysis'&&<div className="factory-inner">{!drama?<Card><Empty description="请先在剧库建立剧目任务"><Button href="/dramas" type="primary">前往剧库</Button></Empty></Card>:!drama.episode_count?<Card className="factory-empty"><Empty description="尚未导入原片"><Button type="primary" icon={<UploadOutlined/>} onClick={()=>setUploadOpen(true)}>选择本地文件夹</Button></Empty></Card>:!analysisReady?<Card className="factory-empty"><Empty description="等待识别"><Button type="primary" loading={busy} onClick={analyze}>识别脚本、高能点与敏感片段</Button></Empty></Card>:<>
      <div className="summary-strip factory-summary"><Statistic title="原片" value={analysis.episode_count} suffix="个"/><Statistic title="总时长" value={clock(analysis.total_duration)}/><Statistic title="脚本片段" value={analysis.segment_count}/><Statistic title="高能点" value={analysis.high_energy_count} valueStyle={{color:'#d97706'}}/><Statistic title="敏感片段" value={analysis.sensitive_count} valueStyle={{color:analysis.sensitive_count?'#c2413b':undefined}}/></div>
      <Card title="逐集时间轴"><Collapse items={analysis.episodes.map(ep=>({key:ep.episode,label:<Space><b>{ep.episode}</b><Tag>{clock(ep.duration)}</Tag>{ep.high_energy.length>0&&<Tag color="orange">高能 {ep.high_energy.length}</Tag>}{ep.sensitive.length>0&&<Tag color="red">敏感 {ep.sensitive.length}</Tag>}</Space>,children:<Table size="small" rowKey={row=>`${ep.episode}-${row.start}`} dataSource={ep.segments} columns={segmentColumns} pagination={false} scroll={{x:760}}/>}))}/></Card>
      <div className="factory-review-grid"><Card title={<><FireOutlined/> 高能候选</>}><Table size="small" rowKey={row=>`${row.episode}-${row.start}`} dataSource={highEnergy} pagination={{pageSize:6}} columns={[{title:'剧集',dataIndex:'episode',width:100},{title:'时间',render:(_,row)=>`${clock(row.start)}–${clock(row.end)}`,width:115},{title:'依据',render:(_,row)=>row.energy_reasons.join('；')||row.text,ellipsis:true},{title:'',width:70,render:(_,row)=><Button size="small" type="primary" onClick={()=>adopt(row.episode,row)}>入库</Button>}]} scroll={{x:650}}/></Card><Card title="待移除敏感片段"><Table size="small" rowKey={row=>`${row.episode}-${row.start}`} dataSource={sensitive} pagination={{pageSize:6}} locale={{emptyText:'未识别到敏感片段'}} columns={[{title:'剧集',dataIndex:'episode',width:95},{title:'时间',render:(_,row)=>`${clock(row.start)}–${clock(row.end)}`,width:110},{title:'风险',render:(_,row)=>Object.entries(row.sensitive).map(([kind,words])=><Tag color="red" key={kind}>{kind} · {words.join('、')}</Tag>)}]} scroll={{x:560}}/></Card></div>
    </>}</div>}

    {tab==='process'&&<div className="factory-inner"><div className="factory-process-grid"><Card title="加工参数"><div className="factory-settings"><label><span>单条上限</span><b>180 秒</b></label><label><span>黄金钩子</span><InputNumber min={1} max={5} value={hookDuration} onChange={v=>setHookDuration(v??3)} addonAfter="秒"/></label><label><span>发布版本</span><InputNumber min={0} max={50} value={variantCount} onChange={v=>setVariantCount(v??0)} addonAfter="个"/></label><label><span>压缩档位</span><Select value={profile} onChange={setProfile} options={[{value:'balanced',label:'均衡 · CRF 23'},{value:'small',label:'省空间 · CRF 28'}]}/></label><label><span>移除敏感片段</span><Switch checked={removeSensitive} onChange={setRemoveSensitive}/></label></div><Select mode="multiple" allowClear value={selectedHooks} onChange={setSelectedHooks} placeholder="不选择时自动按热度取不重复高能点" className="factory-hook-select" options={activeHooks.map(x=>({value:x.id,label:`#${x.id} ${x.drama_title} · ${x.episode} ${clock(x.start)}`}))}/><div className="factory-forecast"><span>预计原剧分段 <b>{forecast||'—'}</b></span><span>差异化版本 <b>{Math.min(variantCount,selectedHooks.length||activeHooks.length,forecast)||0}</b></span><span>数据库视频占用 <b>0 B</b></span></div><Button block size="large" type="primary" icon={<PlayCircleOutlined/>} loading={busy} disabled={!drama?.episode_count||processing} onClick={startProcessing}>{processing?'加工中':'开始拼接与批量生成'}</Button></Card>
      <Card title="当前任务" extra={<Button size="small" icon={<ReloadOutlined/>} disabled={!dramaId} onClick={()=>dramaId&&loadFactory(dramaId)}>刷新</Button>}>{latestJob?<><Space wrap><Tag color={statusColor[latestJob.status]}>{latestJob.status}</Tag><b>#{latestJob.id}</b><span>{latestJob.current_step}</span></Space><Progress percent={latestJob.progress} status={latestJob.status==='failed'?'exception':latestJob.status==='completed'?'success':'active'}/><div className="factory-job-stats"><span>原剧 {latestJob.clean_count}</span><span>发布版 {latestJob.publish_count}</span><span>移除 {clock(latestJob.removed_seconds)}</span><span>输出 {size(latestJob.output_bytes)}</span></div>{latestJob.warnings.map(x=><Alert key={x} type="warning" showIcon message={x}/>) }{latestJob.error_message&&<Alert type="error" showIcon message={latestJob.error_message}/>}</>:<Empty description="暂无加工任务"/>}</Card></div>
      <Card title="已生成"><Table rowKey="id" dataSource={assets} pagination={{pageSize:10}} locale={{emptyText:'任务完成后自动进入剧库“已生成”'}} columns={[{title:'类型',width:95,render:(_,row)=><Tag color={row.kind==='publish'?'blue':'default'}>{row.kind==='publish'?'可发布':'原剧分段'}</Tag>},{title:'文件名',dataIndex:'filename',ellipsis:true},{title:'时长',width:95,render:(_,row)=>clock(row.duration)},{title:'大小',width:100,render:(_,row)=>size(row.size_bytes)},{title:'高能点',width:95,render:(_,row)=>row.hook_asset_id?`#${row.hook_asset_id}`:'—'},{title:'操作',width:190,render:(_,row)=><Space><Button size="small" icon={<DownloadOutlined/>} href={`/api/factory/assets/${row.id}/download`} target="_blank">下载</Button>{row.clip_id&&<Button size="small" type="primary" icon={<RocketOutlined/>} onClick={()=>navigate(`/publishing?drama=${row.drama_id}`)}>发布</Button>}</Space>}]} scroll={{x:760}}/></Card></div>}

    {tab==='hooks'&&<div className="factory-inner"><div className="module-toolbar"><Segmented value={hookScope} onChange={v=>setHookScope(v as typeof hookScope)} options={[{value:'current',label:'当前剧目'},{value:'all',label:'全部剧目'}]}/><Space><Button icon={<ReloadOutlined/>} disabled={!dramaId} onClick={async()=>{if(dramaId)await api.syncFactoryHooks(dramaId);if(dramaId)await loadFactory(dramaId)}}>同步高能点</Button><Button type="primary" loading={busy} disabled={!dramaId} onClick={refreshHookMetrics}>刷新平台表现</Button></Space></div><Card className="table-card"><Table rowKey="id" dataSource={visibleHooks} pagination={{pageSize:12}} columns={[{title:'排名',width:70,render:(_,__,index)=>index+1},{title:'高能点',render:(_,row)=><Space direction="vertical" size={0}><b>#{row.id} · {row.drama_title}</b><Typography.Text type="secondary">{row.episode} · {clock(row.start)}–{clock(row.end)}</Typography.Text></Space>},{title:'依据',dataIndex:'note',ellipsis:true},{title:'热度',width:105,render:(_,row)=><b>{row.heat_score.toLocaleString()}</b>},{title:'发布表现',width:180,render:(_,row)=><Space size={4} wrap><Tag>播放 {row.views.toLocaleString()}</Tag><Tag>赞 {row.likes.toLocaleString()}</Tag><Tag>评 {row.comments.toLocaleString()}</Tag></Space>},{title:'复用',width:80,dataIndex:'use_count'},{title:'状态',width:90,render:(_,row)=><Switch size="small" checked={row.active} onChange={value=>toggleHook(row,value)}/>},{title:'预览',width:80,render:(_,row)=>row.preview_ready?<Button size="small" href={`/api/factory/hooks/${row.id}/video`} target="_blank">查看</Button>:'待生成'}]} scroll={{x:1000}}/></Card></div>}

    <Modal title={`导入原片 · ${drama?.title??''}`} open={uploadOpen} onCancel={()=>!busy&&setUploadOpen(false)} footer={null} width={680} destroyOnHidden><Upload.Dragger directory multiple beforeUpload={()=>false} fileList={sourceFiles.map((file,index)=>({uid:`${index}-${file.name}`,name:file.webkitRelativePath||file.name,status:'done',originFileObj:file as any}))} onChange={({fileList})=>setSourceFiles(fileList.map(x=>x.originFileObj).filter(Boolean) as File[])} accept=".mp4,.mov,.mkv,.webm,.srt,.vtt,.jpg,.jpeg,.png,.webp"><p className="ant-upload-drag-icon"><FolderOpenOutlined/></p><p className="ant-upload-text">选择包含多集原片的本地文件夹</p></Upload.Dragger>{sourceFiles.map(file=><div key={file.webkitRelativePath||file.name} className="upload-file"><span>{file.webkitRelativePath||file.name}</span><Progress percent={uploadProgress[file.name]??0}/></div>)}<Button block size="large" type="primary" loading={busy} disabled={!sourceFiles.length} onClick={uploadSources}>按文件名顺序导入 {sourceFiles.length||''}</Button></Modal>
  </div>
}
