import { useEffect,useMemo,useRef,useState } from 'react'
import { Alert,Button,Card,Collapse,Empty,Image,InputNumber,message,Modal,Popconfirm,Progress,Segmented,Select,Slider,Space,Statistic,Switch,Table,Tag,Typography } from 'antd'
import { CheckCircleFilled,CloseCircleOutlined,CloudUploadOutlined,DownloadOutlined,ExportOutlined,EyeOutlined,FileSearchOutlined,FireOutlined,FolderOpenOutlined,PlayCircleOutlined,ReloadOutlined,RocketOutlined,ScissorOutlined,VideoCameraOutlined } from '@ant-design/icons'
import { useNavigate,useSearchParams } from 'react-router-dom'
import { api,Drama,FactoryAnalysis,FactoryJob,FactoryOutputMode,GeneratedAsset,HookAsset,ScriptSegment } from '../api'
import { localAssistantSupports,localAssistantUnavailable,localWorkspace as localClient,LocalWorkspace,META_DURATION_GUARD_CAPABILITY,NATIVE_FOLDER_PICKER_CAPABILITY } from '../localWorkspace'
import { LOCAL_ASSISTANT_DOWNLOAD_FILENAME,LOCAL_ASSISTANT_DOWNLOAD_URL,showLocalAssistantAccessPrompt,showLocalAssistantInstallPrompt } from '../components/LocalAssistantPrompt'

const clock=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));const hours=Math.floor(value/3600);const minutes=Math.floor((value%3600)/60);const rest=value%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`}
const size=(bytes:number)=>bytes>=1024**3?`${(bytes/1024**3).toFixed(2)} GB`:bytes>=1024**2?`${(bytes/1024**2).toFixed(1)} MB`:`${Math.round(bytes/1024)} KB`
const edgeFrames=(files:string[]=[]):string[]=>files.length<=2?files:[files[0],files[files.length-1]]
const statusColor:Record<string,string>={queued:'default',processing:'blue',cancel_requested:'orange',cancelled:'default',completed:'green',failed:'red'}
const statusLabel:Record<string,string>={queued:'排队中',processing:'加工中',cancel_requested:'取消中',cancelled:'已取消',completed:'已完成',failed:'失败'}
const assetLabels:Record<GeneratedAsset['kind'],{text:string;color:string}>={clean_full:{text:'完整净化版',color:'green'},hook_full:{text:'高能片头版',color:'blue'},meta_episode:{text:'Meta 单集',color:'gold'}}
type FactoryOutputRow=GeneratedAsset&{meta_folder?:boolean;meta_episode_count?:number;meta_assets?:GeneratedAsset[]}
const reviewLabel:Record<string,{text:string;color:string}>={pending:{text:'待复核',color:'gold'},approved:{text:'已采用',color:'green'},rejected:{text:'已排除',color:'default'}}
const sensitiveReviewLabel:Record<string,{text:string;color:string}>={pending:{text:'默认移除',color:'gold'},approved:{text:'已标记移除',color:'red'},rejected:{text:'已保留',color:'green'}}
const riskScoreLabel:Record<string,string>={body_focus:'人体聚焦',action:'动作',dialogue_context:'语境',expression_audio:'表情氛围',scene_context:'场景'}
const FACTORY_CANCEL_CAPABILITY='factory_cancel_v1'
const FACTORY_MODEL_PROXY_CAPABILITY='factory_model_proxy_v1'
const FACTORY_SENSITIVE_POLICY_CAPABILITY='factory_sensitive_policy_v2'

export default function ContentFactory(){
  const[params]=useSearchParams();const navigate=useNavigate()
  const[dramas,setDramas]=useState<Drama[]>([]);const[dramaId,setDramaId]=useState<number>();const[analysis,setAnalysis]=useState<FactoryAnalysis>()
  const[jobs,setJobs]=useState<FactoryJob[]>([]);const[assets,setAssets]=useState<GeneratedAsset[]>([]);const[hooks,setHooks]=useState<HookAsset[]>([])
  const[busy,setBusy]=useState(false);const[cancelling,setCancelling]=useState<number>();const[clouding,setClouding]=useState<number>();const[tab,setTab]=useState<'analysis'|'process'|'hooks'>('analysis');const[hookScope,setHookScope]=useState<'current'|'all'>('current')
  const[localSource,setLocalSource]=useState<LocalWorkspace>();const[localStatus,setLocalStatus]=useState<'checking'|'ready'|'offline'|'outdated'|'unavailable'|'none'>('checking');const[localIssue,setLocalIssue]=useState('')
  const[outputModes,setOutputModes]=useState<FactoryOutputMode[]>(['clean_full','hook_variants']);const[hooksPerVariant,setHooksPerVariant]=useState(1);const[variantCount,setVariantCount]=useState(3)
  const[profile,setProfile]=useState<'balanced'|'small'>('balanced');const[removeSensitive,setRemoveSensitive]=useState(true);const[selectedHooks,setSelectedHooks]=useState<number[]>([])
  const[reviewEpisode,setReviewEpisode]=useState('');const[sensitiveIndex,setSensitiveIndex]=useState(0);const[editRange,setEditRange]=useState<[number,number]>([0,1]);const[videoTime,setVideoTime]=useState(0);const[reviewSaving,setReviewSaving]=useState(false);const videoRef=useRef<HTMLVideoElement>(null);const reviewWorkbenchRef=useRef<HTMLDivElement>(null);const lastSyncedAnalysis=useRef('');const lastSyncedUsage=useRef('');const autoResumedAnalysis=useRef('')
  const[metaPreviewAssets,setMetaPreviewAssets]=useState<GeneratedAsset[]>([]);const[metaPreviewId,setMetaPreviewId]=useState<number>()
  const factoryRequest=useRef(0);const dramaRequest=useRef(0);const selectedDrama=useRef<number|undefined>(undefined)
  selectedDrama.current=dramaId
  const[msg,holder]=message.useMessage();const drama=dramas.find(x=>x.id===dramaId);const usingLocal=Boolean(localSource);const sourceCount=localSource?.file_count??drama?.episode_count??0;const latestJob=jobs[0];const processing=jobs.some(x=>['queued','processing','cancel_requested'].includes(x.status));const analysisPending=['queued','processing'].includes(analysis?.status??'');const analyzing=analysisPending&&analysis?.is_active!==false;const analysisInterrupted=analysisPending&&analysis?.is_active===false
  const radarReference=params.get('radar_video')?{videoId:params.get('radar_video'),episode:params.get('episode')||'',start:Number(params.get('start')||0),end:Number(params.get('end')||0),title:params.get('reference')||''}:undefined

  const chooseDrama=(id?:number)=>{factoryRequest.current+=1;autoResumedAnalysis.current='';selectedDrama.current=id;setLocalSource(undefined);setLocalStatus(id?'checking':'none');setAnalysis(undefined);setJobs([]);setAssets([]);setHooks([]);setSelectedHooks([]);setDramaId(id)}
  const reloadDramas=async(preferred=dramaId,refresh=false)=>{const requestId=++dramaRequest.current;const items=await api.list(refresh);if(requestId!==dramaRequest.current)return items;setDramas(items);const requested=Number(params.get('drama'));const next=items.some(x=>x.id===preferred)?preferred:items.some(x=>x.id===requested)?requested:items[0]?.id;if(next!==selectedDrama.current)chooseDrama(next);return items}
  const syncLocalUsage=async()=>{const events=await localClient.modelUsage();const key=events.at(-1)?.client_event_id??'';if(!key||lastSyncedUsage.current===key)return;for(let index=0;index<events.length;index+=100)await api.sendTelemetry(events.slice(index,index+100));lastSyncedUsage.current=key}
  const loadFactory=async(id:number,local=usingLocal)=>{const requestId=++factoryRequest.current;let a=local?await localClient.factoryAnalysis(id):await api.factoryAnalysis(id);if(local&&a.status==='not_analyzed'){const shared=await api.factoryAnalysis(id);if(shared.status==='completed'){try{a=await localClient.importFactoryAnalysis(id,shared);if(requestId===factoryRequest.current&&selectedDrama.current===id)msg.success('已复用云端识别结果，无需重复消耗模型次数')}catch{/* 文件名不同则保留本机待识别状态 */}}}const[j,g,h]=await Promise.all([local?localClient.factoryJobs(id):api.factoryJobs(id),local?localClient.factoryAssets(id):api.factoryAssets(id),api.factoryHooks()]);if(requestId!==factoryRequest.current||selectedDrama.current!==id)return false;setAnalysis(a);setJobs(j);setAssets(g);setHooks(h);const syncKey=`${id}:${a.updated_at??a.generated_at??''}:${a.status}`;if(local&&a.status==='completed'&&!a.reused_from_cloud&&lastSyncedAnalysis.current!==syncKey){lastSyncedAnalysis.current=syncKey;api.importLocalFactoryAnalysis(id,a).catch(()=>{lastSyncedAnalysis.current=''})}if(local)syncLocalUsage().catch(()=>undefined);return true}
  const pollFactory=async(id:number,local:boolean)=>{const requestId=++factoryRequest.current;const[a,j]=await Promise.all([local?localClient.factoryAnalysis(id):api.factoryAnalysis(id),local?localClient.factoryJobs(id):api.factoryJobs(id)]);if(requestId!==factoryRequest.current||selectedDrama.current!==id)return;setAnalysis(a);setJobs(j);const active=['queued','processing'].includes(a.status)&&a.is_active!==false||j.some(item=>['queued','processing','cancel_requested'].includes(item.status));if(!active)await loadFactory(id,local)}
  useEffect(()=>{reloadDramas(undefined).catch(e=>msg.error(e.message))},[])
  useEffect(()=>{if(!dramaId){setLocalSource(undefined);setLocalStatus('none');return}let cancelled=false;setLocalStatus('checking');localClient.health().then(health=>{if(!localAssistantSupports(health,NATIVE_FOLDER_PICKER_CAPABILITY)||!localAssistantSupports(health,FACTORY_CANCEL_CAPABILITY)||!localAssistantSupports(health,FACTORY_MODEL_PROXY_CAPABILITY)||!localAssistantSupports(health,FACTORY_SENSITIVE_POLICY_CAPABILITY)||!localAssistantSupports(health,META_DURATION_GUARD_CAPABILITY))throw new Error('本地助手需要更新');if(health.picker_ready===false)throw new Error('本地助手未运行在当前 Windows 用户桌面');return localClient.get(dramaId)}).then(value=>{if(!cancelled){setLocalSource(value);setLocalStatus('ready')}}).catch(error=>{if(cancelled)return;setLocalSource(undefined);const text=(error as Error).message;setLocalStatus(localAssistantUnavailable(error)?'offline':text.includes('需要更新')?'outdated':text.includes('当前 Windows 用户桌面')?'unavailable':'none')});return()=>{cancelled=true}},[dramaId])
  useEffect(()=>{if(!dramaId){setAnalysis(undefined);setJobs([]);setAssets([]);return}if(localStatus==='checking')return;loadFactory(dramaId,Boolean(localSource)).catch(e=>msg.error(e.message))},[dramaId,localStatus,localSource?.absolute_path])
  useEffect(()=>{if(!dramaId||(!processing&&!analyzing))return;const local=usingLocal;const timer=window.setInterval(()=>{if(document.visibilityState==='visible')pollFactory(dramaId,local).catch(()=>undefined)},5000);return()=>window.clearInterval(timer)},[dramaId,processing,analyzing,usingLocal])

  const syncLocalAnalysis=async(result:FactoryAnalysis)=>{if(!dramaId||result.status!=='completed')return;try{await api.importLocalFactoryAnalysis(dramaId,result)}catch{/* 本机结果保留，下一次轮询继续尝试同步 */}}
  const analyze=async()=>{if(!dramaId)return;setBusy(true);try{if(usingLocal){const health=await localClient.health();if(!localAssistantSupports(health,FACTORY_MODEL_PROXY_CAPABILITY)){setLocalStatus('outdated');throw new Error('请更新本地助手后使用服务器模型识别')}}const result=usingLocal?await localClient.analyzeFactory(dramaId,await api.factoryAnalysisAccess()):await api.analyzeFactory(dramaId);setAnalysis(result);msg.success(usingLocal?'已在本机开始识别，源视频不会上传':'识别任务已开始，可留在本页查看进度')}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  useEffect(()=>{if(!dramaId||!usingLocal||!analysisInterrupted||busy||localStatus!=='ready')return;const key=String(dramaId);if(autoResumedAnalysis.current===key)return;autoResumedAnalysis.current=key;analyze().catch(()=>undefined)},[dramaId,usingLocal,analysisInterrupted,busy,localStatus])
  const adopt=async(episode:string,segment:ScriptSegment)=>{if(!drama)return;const duplicate=drama.highlights.some(x=>x.episode===episode&&Math.abs(x.start-segment.start)<.1);if(duplicate)return msg.info('该高能点已在库中');try{const reviewed=usingLocal?await localClient.reviewFactoryAnalysis(drama.id,{episode,kind:'high_energy',start:segment.start,end:segment.end,decision:'approved'}):await api.reviewFactoryAnalysis(drama.id,{episode,kind:'high_energy',start:segment.start,end:segment.end,decision:'approved'});if(usingLocal)await syncLocalAnalysis(reviewed);const updated=await api.highlights(drama.id,[...drama.highlights,{episode,start:segment.start,end:segment.end,note:segment.energy_reasons.join('；')||segment.text.slice(0,60)}]);setDramas(items=>items.map(x=>x.id===updated.id?updated:x));await api.syncFactoryHooks(drama.id);await loadFactory(drama.id);msg.success('已加入高能库')}catch(e){msg.error((e as Error).message)}}
  const reviewCandidate=async(episode:string,kind:'high_energy'|'sensitive',segment:ScriptSegment,decision:'approved'|'rejected')=>{if(!dramaId)return;try{const updated=usingLocal?await localClient.reviewFactoryAnalysis(dramaId,{episode,kind,start:segment.start,end:segment.end,decision}):await api.reviewFactoryAnalysis(dramaId,{episode,kind,start:segment.start,end:segment.end,decision});setAnalysis(updated);if(usingLocal)await syncLocalAnalysis(updated);if(kind==='high_energy'&&decision==='approved')await api.syncFactoryHooks(dramaId);msg.success(kind==='sensitive'?(decision==='approved'?'已标记为移除，生成净化版时自动删除':'已标记为保留'):(decision==='approved'?'已采用该片段':'已排除该片段'))}catch(e){msg.error((e as Error).message)}}
  const connectLocalSource=async()=>{if(!drama)return;setBusy(true);setLocalStatus('checking');setLocalIssue('');try{
    msg.loading({key:'local-access',content:'正在连接本地助手；若浏览器询问本地网络访问，请点“允许”',duration:0})
    let health
    try{health=await localClient.requestAccess()}catch(error){msg.destroy('local-access');const text=(error as Error).message;setLocalIssue(text);if(localAssistantUnavailable(error)){setLocalStatus('offline');showLocalAssistantAccessPrompt()}else{setLocalStatus('none');msg.error(text)}return}
    if(!localAssistantSupports(health,NATIVE_FOLDER_PICKER_CAPABILITY)||!localAssistantSupports(health,FACTORY_CANCEL_CAPABILITY)||!localAssistantSupports(health,FACTORY_MODEL_PROXY_CAPABILITY)||!localAssistantSupports(health,FACTORY_SENSITIVE_POLICY_CAPABILITY)||!localAssistantSupports(health,META_DURATION_GUARD_CAPABILITY)){msg.destroy('local-access');setLocalStatus('outdated');setLocalIssue('当前本地助手版本较旧，请安装新版后重试');showLocalAssistantInstallPrompt({mode:'update'});return}
    if(health.picker_ready===false){msg.destroy('local-access');setLocalStatus('unavailable');setLocalIssue(`本地助手不在当前 Windows 桌面会话（${health.picker_reason||'unknown'}），请双击桌面快捷方式后重试`);msg.warning('本地助手未运行在当前 Windows 用户桌面，请双击桌面上的“Jushu Local Assistant”后重试');return}
    msg.destroy('local-access')
    setLocalStatus('ready')
    msg.loading({key:'folder-picker',content:'请在已打开的 Windows 窗口中选择源文件夹；若窗口不在前台，请查看任务栏',duration:0})
    const selected=await localClient.select(drama);msg.destroy('folder-picker');setLocalSource(selected);setLocalStatus('ready');setLocalIssue('');await api.registerLocalSourceManifest(drama.id,{folder_name:selected.folder_name,file_count:selected.file_count,total_bytes:selected.total_bytes,filenames:selected.files.map(file=>file.relative_path)});await reloadDramas(drama.id,true);await loadFactory(drama.id,true);msg.success(`已连接本地文件夹，共 ${selected.file_count} 集；视频未上传服务器`)
  }catch(e){msg.destroy('local-access');msg.destroy('folder-picker');const text=(e as Error).message;if(localAssistantUnavailable(e)){setLocalStatus('offline');setLocalIssue(text);showLocalAssistantAccessPrompt()}else{setLocalStatus(localSource?'ready':'none');if(text.includes('取消选择')){setLocalIssue('没有选择文件夹。请重新点击按钮，并在弹出的 Windows 窗口中完成选择。');msg.info('已取消选择文件夹')}else{setLocalIssue(text);msg.error(text)}}}finally{setBusy(false)}}
  const toggleMode=(mode:FactoryOutputMode)=>setOutputModes(current=>current.includes(mode)?current.filter(x=>x!==mode):[...current,mode])
  const startProcessing=async()=>{if(!dramaId)return;if(!outputModes.length)return msg.warning('至少选择一种产出流程');if(removeSensitive&&outputModes.some(x=>x!=='meta_split')&&analysis?.status!=='completed')return msg.warning('请先完成敏感内容识别');setBusy(true);try{const body={max_duration_seconds:180,hook_duration_seconds:15,publish_variant_count:variantCount,remove_sensitive:removeSensitive,compression_profile:profile,output_modes:outputModes,hooks_per_variant:hooksPerVariant,hook_ids:usingLocal?[]:selectedHooks};const job=usingLocal?await localClient.startFactoryProcessing(dramaId,body):await api.startFactoryProcessing(dramaId,body);setJobs(old=>[job,...old]);setTab('process');msg.success(usingLocal?`本机加工任务 #${job.id} 已开始，成品保存在源文件夹内`:`加工任务 #${job.id} 已开始`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const cancelProcessing=async(job:FactoryJob)=>{if(!dramaId)return;setCancelling(job.id);try{const updated=usingLocal?await localClient.cancelFactoryJob(job.id):await api.cancelFactoryJob(job.id);setJobs(items=>items.map(item=>item.id===updated.id?updated:item));msg.success(updated.status==='cancelled'?'任务已取消':'正在停止处理并清理中间文件');await loadFactory(dramaId)}catch(e){msg.error((e as Error).message)}finally{setCancelling(undefined)}}
  const toggleHook=async(row:HookAsset,active:boolean)=>{try{const changed=await api.setFactoryHookActive(row.id,active);setHooks(items=>items.map(x=>x.id===changed.id?changed:x))}catch(e){msg.error((e as Error).message)}}
  const refreshHookMetrics=async()=>{if(!dramaId)return;setBusy(true);try{const result=await api.collectMetrics(true);await loadFactory(dramaId);msg.success(`平台数据已刷新 ${result.created+result.updated} 条`)}catch(e){msg.error((e as Error).message)}finally{setBusy(false)}}
  const uploadCloud=async(asset:GeneratedAsset)=>{setClouding(asset.id);try{await api.uploadCloudAsset(asset.id);msg.success('已上传云剧库，所有账号均可查看下载')}catch(e){msg.error((e as Error).message)}finally{setClouding(undefined)}}
  const assetUrl=(id:number)=>usingLocal?localClient.assetUrl(id):`/api/factory/assets/${id}/download`
  const handoffToJianying=(row:GeneratedAsset)=>{const link=document.createElement('a');link.href=assetUrl(row.id);link.download=row.filename;document.body.appendChild(link);link.click();link.remove();window.open('https://www.jianying.com/','_blank','noopener,noreferrer');msg.success(usingLocal?'已打开本机成品并跳转剪映':'成品已开始下载')}

  const highEnergy=useMemo(()=>(analysis?.episodes.flatMap(ep=>ep.high_energy.map(row=>({episode:ep.episode,...row})))??[]).sort((a,b)=>b.energy_score-a.energy_score).slice(0,10),[analysis]);const sensitive=useMemo(()=>analysis?.episodes.flatMap(ep=>ep.sensitive.map(row=>({episode:ep.episode,...row})))??[],[analysis]);const analysisReady=analysis?.status==='completed'&&!analysis.requires_reanalysis;const pendingSensitive=sensitive.filter(row=>row.review_status==='pending').length
  const visibleHooks=useMemo(()=>hooks.filter(x=>hookScope==='all'||x.drama_id===dramaId),[hooks,hookScope,dramaId]);const activeHooks=hooks.filter(x=>x.active);const metaForecast=analysisReady?analysis.episodes.reduce((sum,ep)=>sum+Math.ceil(ep.duration/180),0):undefined
  const outputRows=useMemo<FactoryOutputRow[]>(()=>{
    const regular=assets.filter(row=>row.kind!=='meta_episode') as FactoryOutputRow[]
    const meta=assets.filter(row=>row.kind==='meta_episode')
    if(!meta.length)return regular
    const latestJobId=Math.max(...meta.map(row=>row.factory_job_id))
    const latest=meta.filter(row=>row.factory_job_id===latestJobId).sort((a,b)=>a.sequence-b.sequence)
    const first=latest[0]
    const folder:FactoryOutputRow={
      ...first,
      id:-latestJobId,
      filename:`J${String(latestJobId).padStart(4,'0')}_Meta投递文件夹`,
      duration:latest.reduce((sum,row)=>sum+row.duration,0),
      size_bytes:latest.reduce((sum,row)=>sum+row.size_bytes,0),
      meta_folder:true,
      meta_episode_count:latest.length,
      meta_assets:latest,
    }
    return [folder,...regular].sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime())
  },[assets])
  const activeEpisode=useMemo(()=>analysis?.episodes.find(ep=>ep.episode===reviewEpisode)??analysis?.episodes[0],[analysis,reviewEpisode]);const activeSensitive=activeEpisode?.sensitive??[];const selectedSensitive=activeSensitive[sensitiveIndex]
  useEffect(()=>{const episodes=analysis?.episodes??[];if(!episodes.length){setReviewEpisode('');return}if(!episodes.some(ep=>ep.episode===reviewEpisode)){setReviewEpisode(episodes[0].episode);setSensitiveIndex(0)}},[analysis,reviewEpisode])
  useEffect(()=>{const row=activeSensitive[sensitiveIndex]??activeSensitive[0];if(!row){setSensitiveIndex(0);setEditRange([0,Math.min(1,activeEpisode?.duration??1)]);return}if(!activeSensitive[sensitiveIndex])setSensitiveIndex(0);setEditRange([row.start,row.end])},[activeEpisode?.episode,analysis,sensitiveIndex])
  const seekVideo=(second:number)=>{const next=Math.max(0,Math.min(second,activeEpisode?.duration??second));if(videoRef.current)videoRef.current.currentTime=next;setVideoTime(next)}
  const chooseSensitive=(index:number)=>{const row=activeSensitive[index];if(!row)return;setSensitiveIndex(index);setEditRange([row.start,row.end]);seekVideo(row.start)}
  const openSensitive=(episode:string,row:ScriptSegment)=>{const target=analysis?.episodes.find(item=>item.episode===episode);if(!target)return;const index=Math.max(0,target.sensitive.findIndex(item=>Math.abs(item.start-row.start)<.05&&Math.abs(item.end-row.end)<.05));setReviewEpisode(episode);setSensitiveIndex(index);setEditRange([row.start,row.end]);setVideoTime(row.start);window.setTimeout(()=>{if(videoRef.current)videoRef.current.currentTime=row.start;reviewWorkbenchRef.current?.scrollIntoView({behavior:'smooth',block:'start'})},0)}
  const saveSensitiveRange=async(value:number[])=>{if(!dramaId||!activeEpisode||!selectedSensitive)return;const maximum=Math.max(.2,activeEpisode.duration);const start=Math.max(0,Math.min(Number(value[0].toFixed(1)),maximum-.2));const end=Math.min(maximum,Math.max(start+.2,Number(value[1].toFixed(1))));setEditRange([start,end]);if(Math.abs(start-selectedSensitive.start)<.05&&Math.abs(end-selectedSensitive.end)<.05)return;setReviewSaving(true);try{const body={episode:activeEpisode.episode,kind:'sensitive' as const,start:selectedSensitive.start,end:selectedSensitive.end,decision:'approved' as const,new_start:start,new_end:end};const updated=usingLocal?await localClient.reviewFactoryAnalysis(dramaId,body):await api.reviewFactoryAnalysis(dramaId,body);setAnalysis(updated);if(usingLocal)await syncLocalAnalysis(updated);msg.success(`剪除区间已更新为 ${clock(start)}–${clock(end)}`)}catch(e){setEditRange([selectedSensitive.start,selectedSensitive.end]);msg.error((e as Error).message)}finally{setReviewSaving(false)}}
  const segmentColumns=[{title:'时间',width:115,render:(_:unknown,row:ScriptSegment)=>`${clock(row.start)}–${clock(row.end)}`},{title:'脚本',dataIndex:'text'},{title:'高能',width:90,render:(_:unknown,row:ScriptSegment)=>row.high_energy?<Tag color="orange">{row.energy_score.toFixed(1)}</Tag>:'—'},{title:'敏感内容',width:210,render:(_:unknown,row:ScriptSegment)=>Object.entries(row.sensitive).length?Object.entries(row.sensitive).map(([kind,words])=><Tag color="red" key={kind}>{kind} · {words.join('、')}</Tag>):'—'}]

  return <div className="workspace-page factory-page">{holder}
    <div className="page-heading page-heading-rich"><Typography.Title level={2}>内容工厂</Typography.Title><Space wrap><Select showSearch optionFilterProp="label" placeholder="选择剧目任务" value={dramaId} onChange={chooseDrama} options={dramas.map(x=>({value:x.id,label:x.title}))} style={{width:240}}/><Button icon={<FolderOpenOutlined/>} loading={busy} disabled={!drama} onClick={connectLocalSource}>{usingLocal?'更换本地文件夹':'选择本地文件夹'}</Button>{localStatus==='outdated'&&<Button href={LOCAL_ASSISTANT_DOWNLOAD_URL} download={LOCAL_ASSISTANT_DOWNLOAD_FILENAME} onClick={()=>msg.success('已开始下载最新版本地助手')}>更新本地助手</Button>}{localStatus==='unavailable'&&<Button onClick={connectLocalSource}>重新连接助手</Button>}<Button type="primary" icon={<FileSearchOutlined/>} loading={busy||analyzing} disabled={!sourceCount||analyzing||localStatus==='checking'||localStatus==='outdated'||localStatus==='unavailable'} onClick={analyze}>{analyzing?'AI 识别中':analysisInterrupted?'继续识别':analysisReady?'重新识别':'识别整部剧'}</Button></Space></div>
    {drama&&<div className="factory-task-strip"><b>{drama.title}</b><Tag color={usingLocal?'green':drama.episode_count?'blue':'default'}>{usingLocal?'本地工作区':drama.episode_count?'服务器旧素材':'未连接源文件'}</Tag><span>源文件 {sourceCount}</span><span>登记集数 {drama.total_episode_count}</span><span>我的成品 {assets.length}</span>{usingLocal&&<Typography.Text ellipsis={{tooltip:localSource?.absolute_path}}>{localSource?.folder_name} · {size(localSource?.total_bytes??0)}</Typography.Text>}{drama.genres.map(genre=><Tag key={genre}>{genre}</Tag>)}</div>}
    {localIssue&&<Alert showIcon closable type={localStatus==='offline'||localStatus==='outdated'||localStatus==='unavailable'?'warning':'info'} message={localIssue} onClose={()=>setLocalIssue('')} style={{marginBottom:12}}/>}
    <Segmented block className="overview-pager factory-pager" value={tab} onChange={value=>setTab(value as typeof tab)} options={[{value:'analysis',label:'1 内容识别'},{value:'process',label:'2 产出流程'},{value:'hooks',label:'3 高能库'}]}/>
    {radarReference&&<Alert showIcon type="info" message="已接收平台动态参考" description={<span>{radarReference.title||`外部视频 #${radarReference.videoId}`}{radarReference.episode?` · ${radarReference.episode} ${clock(radarReference.start)}–${clock(radarReference.end)}`:' · 尚未指定原片区间'}。请核对原片后再开始生成，系统不会自动加工。</span>}/>}

    {tab==='analysis'&&<div className="factory-inner">{!drama?<Card><Empty description="请先在剧库建立剧目任务"><Button href="/dramas" type="primary">前往剧库</Button></Empty></Card>:!sourceCount?<Card className="factory-empty"><Empty description="选择电脑里的源文件夹，视频不会上传服务器"><Button type="primary" icon={<FolderOpenOutlined/>} loading={busy} disabled={busy} onClick={connectLocalSource}>选择本地文件夹</Button></Empty></Card>:analyzing?<Card className="factory-analysis-progress" title={usingLocal?'本机 AI 正在识别整部剧':'AI 正在识别整部剧'}><Progress percent={analysis?.progress??0} status="active"/><b>{analysis?.current_step||'准备本地转写与抽帧'}</b><div className="factory-analysis-live"><span>已完成剧集 {analysis?.episodes.length??0}/{analysis?.episode_count??sourceCount}</span><span>已抽帧 {analysis?.sampled_frame_count??0}</span><span>模型调用 {analysis?.api_call_count??0}</span>{Boolean(analysis?.resume_count)&&<span>已自动续跑 {analysis?.resume_count} 次</span>}</div></Card>:analysisInterrupted?<Card className="factory-empty"><Alert type="info" showIcon message="正在恢复上次识别" description={(analysis?.episodes.length??0)>0?`已保存 ${analysis?.episodes.length??0} 集结果，将从断点自动继续。`:'上次任务尚未产出结果，正在使用新的授权重新启动。'}/><Button type="primary" loading={busy} onClick={analyze}>立即重试</Button></Card>:analysis?.status==='failed'?<Card className="factory-empty"><Alert type="error" showIcon message="内容识别中断" description={analysis.error_message}/><Button type="primary" onClick={analyze}>从断点继续</Button></Card>:!analysisReady?<Card className="factory-empty">{analysis?.ai_ready===false&&<Alert type="warning" showIcon message="尚未配置多模态模型" description="配置 GEMINI_API_KEY 或 QWEN_API_KEY 后即可结合脚本和抽帧识别。"/>}{analysis?.requires_reanalysis&&<Alert type="info" showIcon message="需要升级识别结果" description="已有结果只分析了对白和音量，请重新识别以加入真实画面判断。"/>}<Empty description="等待识别"><Button type="primary" loading={busy} onClick={analyze}>识别脚本、抽帧、高能点与敏感片段</Button></Empty></Card>:<>
      <div className="summary-strip factory-summary"><Statistic title="源文件" value={analysis.episode_count} suffix="集"/><Statistic title="总时长" value={clock(analysis.total_duration)}/><Statistic title="脚本片段" value={analysis.segment_count}/><Statistic title="证据抽帧" value={analysis.sampled_frame_count}/><Statistic title="高能点" value={analysis.high_energy_count} valueStyle={{color:'#d97706'}}/><Statistic title="敏感片段" value={analysis.sensitive_count} valueStyle={{color:analysis.sensitive_count?'#c2413b':undefined}}/></div>
      <div className="factory-analysis-meta"><Tag color="blue">{analysis.provider} · {analysis.model}</Tag><span>模型调用 {analysis.api_call_count} 次</span>{pendingSensitive>0&&<Tag color="gold">{pendingSensitive} 个低置信风险待复核</Tag>}</div>
      <div ref={reviewWorkbenchRef}><Card className="factory-review-workbench" title="逐集敏感复核" extra={activeEpisode&&<span className="factory-review-counter">{activeEpisode.episode} · {activeSensitive.length} 个标记</span>}>
        <div className="factory-review-layout">
          <aside className="factory-episode-list" aria-label="剧集列表">{analysis.episodes.map((ep,index)=><button type="button" key={ep.episode} className={ep.episode===activeEpisode?.episode?'is-active':''} onClick={()=>{setReviewEpisode(ep.episode);setSensitiveIndex(0);setVideoTime(0)}}><span>{String(index+1).padStart(2,'0')}</span><div><b>{ep.episode}</b><small>{clock(ep.duration)} · {ep.sensitive.length} 个敏感标记</small></div>{ep.sensitive.some(row=>row.review_status==='pending')&&<i/>}</button>)}</aside>
          {activeEpisode&&<section className="factory-video-review">
            <div className="factory-video-stage"><video key={activeEpisode.episode} ref={videoRef} controls playsInline preload="metadata" src={usingLocal?localClient.videoUrl(drama.id,activeEpisode.episode):`/api/factory/${drama.id}/analysis/video/${encodeURIComponent(activeEpisode.episode)}`} onTimeUpdate={event=>setVideoTime(event.currentTarget.currentTime)} onLoadedMetadata={event=>{if(editRange[0]>0)event.currentTarget.currentTime=editRange[0]}}/></div>
            <div className="factory-video-review-panel">
            <div className="factory-timeline-heading"><b>敏感片段时间轴</b><span>{clock(videoTime)} / {clock(activeEpisode.duration)}</span></div>
            <div className="factory-sensitive-track" onClick={event=>{const bounds=event.currentTarget.getBoundingClientRect();seekVideo((event.clientX-bounds.left)/bounds.width*activeEpisode.duration)}}>
              {activeSensitive.map((row,index)=>{const duration=Math.max(.2,activeEpisode.duration);const left=Math.max(0,Math.min(100,row.start/duration*100));const width=Math.max(.7,Math.min(100-left,(row.end-row.start)/duration*100));return <button type="button" key={`${row.start}-${row.end}-${index}`} title={`${clock(row.start)}–${clock(row.end)}`} aria-label={`敏感片段 ${clock(row.start)} 到 ${clock(row.end)}`} className={`${index===sensitiveIndex?'is-selected':''} ${row.review_status==='rejected'?'is-kept':''}`} style={{left:`${left}%`,width:`${width}%`}} onClick={event=>{event.stopPropagation();chooseSensitive(index)}}/>})}
              <i className="factory-playhead" style={{left:`${Math.min(100,videoTime/Math.max(.2,activeEpisode.duration)*100)}%`}}/>
            </div>
            {selectedSensitive?<div className="factory-range-editor">
              <div className="factory-range-title"><div><b>调整剪除范围</b><span>拖动左右端点，松开后自动保存并标记为移除</span></div><strong>{clock(editRange[0])} – {clock(editRange[1])}</strong></div>
              <Slider range min={0} max={Math.max(.2,activeEpisode.duration)} step={.1} value={editRange} disabled={reviewSaving} tooltip={{formatter:value=>clock(value??0)}} onChange={value=>{const next=value as [number,number];const changed=Math.abs(next[0]-editRange[0])>=Math.abs(next[1]-editRange[1])?next[0]:next[1];setEditRange(next);seekVideo(changed)}} onChangeComplete={value=>saveSensitiveRange(value as number[])}/>
            </div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="本集未识别到敏感片段"/>}
            {activeSensitive.length>0&&<div className="factory-sensitive-list">{activeSensitive.map((row,index)=><article key={`${row.start}-${row.end}-${index}`} className={index===sensitiveIndex?'is-active':''}>
              <button type="button" className="factory-sensitive-summary" onClick={()=>chooseSensitive(index)}><span><b>{clock(row.start)}–{clock(row.end)}</b><Tag color={(row.overall_risk_score??0)>=60?'red':'gold'}>风险 {row.overall_risk_score??Math.round((row.confidence??0)*100)}</Tag><Tag color={sensitiveReviewLabel[row.review_status??'pending'].color}>{sensitiveReviewLabel[row.review_status??'pending'].text}</Tag></span><small>{Object.entries(row.sensitive).flatMap(([kind,words])=>words.map(word=>`${kind}：${word}`)).join('；')||row.text}</small>{row.risk_scores&&<span className="factory-risk-scores">{Object.entries(row.risk_scores).filter(([,score])=>(score??0)>0).map(([key,score])=><em key={key}>{riskScoreLabel[key]??key} {score}</em>)}</span>}</button>
              <div className="factory-sensitive-actions"><Button size="small" danger disabled={row.review_status==='approved'} onClick={()=>reviewCandidate(activeEpisode.episode,'sensitive',row,'approved')}>标记移除</Button><Button size="small" disabled={row.review_status==='rejected'} onClick={()=>reviewCandidate(activeEpisode.episode,'sensitive',row,'rejected')}>保留</Button></div>
            </article>)}</div>}
            <Collapse className="factory-script-collapse" items={[{key:'script',label:`展开本集脚本详情（${activeEpisode.segments.length} 段）`,children:<Table size="small" rowKey={row=>`${activeEpisode.episode}-${row.start}`} dataSource={activeEpisode.segments} columns={segmentColumns} pagination={false} scroll={{x:760}}/>}]}/>
            </div>
          </section>}
        </div>
      </Card></div>
      <div className="factory-review-grid factory-candidate-grid"><Card title={`全部敏感内容 · ${sensitive.length}`}>
        {sensitive.length?<div className="factory-sensitive-list factory-sensitive-overview">{sensitive.map((row,index)=><article key={`${row.episode}-${row.start}-${row.end}-${index}`}>
          <button type="button" className="factory-sensitive-summary" onClick={()=>openSensitive(row.episode,row)}>
            <span><b>{row.episode} · {clock(row.start)}–{clock(row.end)}</b><Tag color={(row.overall_risk_score??0)>=60?'red':'gold'}>风险 {row.overall_risk_score??Math.round((row.confidence??0)*100)}</Tag><Tag color={sensitiveReviewLabel[row.review_status??'pending'].color}>{sensitiveReviewLabel[row.review_status??'pending'].text}</Tag></span>
            <small>{Object.entries(row.sensitive).flatMap(([kind,words])=>words.map(word=>`${kind}：${word}`)).join('；')||row.text||'未提供风险说明'}</small>
            {row.risk_scores&&<span className="factory-risk-scores">{Object.entries(row.risk_scores).filter(([,score])=>(score??0)>0).map(([key,score])=><em key={key}>{riskScoreLabel[key]??key} {score}</em>)}</span>}
          </button>
          <div className="factory-sensitive-actions"><Button size="small" danger disabled={row.review_status==='approved'} onClick={()=>reviewCandidate(row.episode,'sensitive',row,'approved')}>标记移除</Button><Button size="small" disabled={row.review_status==='rejected'} onClick={()=>reviewCandidate(row.episode,'sensitive',row,'rejected')}>保留</Button></div>
        </article>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="未识别到敏感内容"/>}
      </Card>
      <Card title={<><FireOutlined/> 高能候选 · {highEnergy.length}</>}>
        {highEnergy.length?<div className="factory-high-energy-list">{highEnergy.map((row,index)=><article key={`${row.episode}-${row.start}-${row.end}-${index}`}>
          <div className="factory-high-energy-main"><span><b>{row.episode} · {clock(row.start)}–{clock(row.end)}</b><Tag color="orange">评分 {row.energy_score.toFixed(0)}</Tag><Tag color={reviewLabel[row.review_status??'pending'].color}>{reviewLabel[row.review_status??'pending'].text}</Tag></span><small>{row.energy_reasons.join('；')||row.text||'未提供高能依据'}</small></div>
          <div className="factory-high-energy-side"><div className="factory-candidate-frames"><Image.PreviewGroup>{edgeFrames(row.frame_files).map(file=><Image key={file} width={44} height={34} src={usingLocal?localClient.frameUrl(drama.id,file):api.factoryFrameUrl(drama.id,file)} style={{objectFit:'cover',borderRadius:6}}/>)}</Image.PreviewGroup></div><div><Button size="small" type="primary" disabled={row.review_status==='approved'} onClick={()=>adopt(row.episode,row)}>采用</Button><Button size="small" disabled={row.review_status==='rejected'} onClick={()=>reviewCandidate(row.episode,'high_energy',row,'rejected')}>排除</Button></div></div>
        </article>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="未识别到高能候选"/>}
      </Card></div>
    </>}</div>}

    {tab==='process'&&<div className="factory-inner">
      <Card title="选择产出方式"><div className="factory-output-grid">
        <button type="button" className={`factory-output-card ${outputModes.includes('clean_full')?'is-selected':''}`} onClick={()=>toggleMode('clean_full')}><span className="factory-output-index">01</span><VideoCameraOutlined/><b>原剧合并净化</b><small>顺序拼接 · 敏感内容去除 · 完整视频</small>{outputModes.includes('clean_full')&&<CheckCircleFilled/>}</button>
        <button type="button" className={`factory-output-card ${outputModes.includes('hook_variants')?'is-selected':''}`} onClick={()=>toggleMode('hook_variants')}><span className="factory-output-index">02</span><FireOutlined/><b>高能片头批量版</b><small>1–3个片头 · 多版本 · 完整视频</small>{outputModes.includes('hook_variants')&&<CheckCircleFilled/>}</button>
        <button type="button" className={`factory-output-card ${outputModes.includes('meta_split')?'is-selected':''}`} onClick={()=>toggleMode('meta_split')}><span className="factory-output-index">03</span><ScissorOutlined/><b>Meta 逐集切分</b><small>不拼接 · 单集≤3分钟 · 自动均分</small>{outputModes.includes('meta_split')&&<CheckCircleFilled/>}</button>
      </div></Card>
      <div className="factory-process-grid"><Card title="加工参数" className="factory-parameter-card">
        <div className={`factory-parameter-layout ${outputModes.includes('hook_variants')?'':'is-single'}`}>
          <section className="factory-parameter-section"><div className="factory-parameter-title"><span>01</span><b>基础设置</b></div><div className="factory-setting-stack">
            <label className="factory-setting-row"><span>压缩档位</span><Select value={profile} onChange={setProfile} options={[{value:'balanced',label:'均衡 · CRF 23'},{value:'small',label:'省空间 · CRF 28'}]}/></label>
            {outputModes.some(x=>x!=='meta_split')&&<label className="factory-setting-row"><span>敏感内容去除</span><Switch checked={removeSensitive} onChange={setRemoveSensitive}/></label>}
            {outputModes.includes('meta_split')&&<label className="factory-setting-row"><span>Meta 单集上限</span><strong>180 秒</strong></label>}
          </div></section>
          {outputModes.includes('hook_variants')&&<section className="factory-parameter-section is-hook"><div className="factory-parameter-title"><span>02</span><b>高能版本</b></div>
            <div className="factory-compact-options"><label><span>每版高能点</span><InputNumber min={1} max={3} value={hooksPerVariant} addonAfter="个" onChange={value=>setHooksPerVariant(value??1)}/></label><label><span>批量版本</span><InputNumber min={1} max={50} value={variantCount} addonAfter="版" onChange={value=>setVariantCount(value??1)}/></label></div>
            <label className="factory-hook-source"><span>高能点来源</span><Select mode="multiple" allowClear value={selectedHooks} onChange={setSelectedHooks} placeholder="自动按评分选择，或手动指定" options={activeHooks.map(x=>({value:x.id,label:`#${x.id} ${x.drama_title} · ${x.episode} ${clock(x.start)}`}))}/></label>
          </section>}
        </div>
        <div className="factory-parameter-footer"><div className="factory-forecast"><div><span>完整净化版</span><strong>{outputModes.includes('clean_full')?1:0}</strong><small>个文件</small></div><div><span>高能片头版</span><strong>{outputModes.includes('hook_variants')?variantCount:0}</strong><small>个文件</small></div><div><span>Meta 单集</span><strong>{outputModes.includes('meta_split')?(metaForecast??'—'):0}</strong><small>个文件</small></div></div><Button size="large" type="primary" icon={<PlayCircleOutlined/>} loading={busy} disabled={!sourceCount||processing||!outputModes.length} onClick={startProcessing}>{processing?'加工中':usingLocal?'开始本机生成':'开始生成所选成品'}</Button></div>
      </Card>
        <Card title="当前任务" extra={<Space><Button size="small" icon={<ReloadOutlined/>} disabled={!dramaId} onClick={()=>dramaId&&loadFactory(dramaId)}>刷新</Button>{latestJob&&['queued','processing','cancel_requested'].includes(latestJob.status)&&<Popconfirm title="取消当前生成任务？" description="已生成的不完整文件会自动清理。" okText="取消任务" cancelText="继续生成" onConfirm={()=>cancelProcessing(latestJob)}><Button size="small" danger icon={<CloseCircleOutlined/>} loading={cancelling===latestJob.id} disabled={latestJob.status==='cancel_requested'}>{latestJob.status==='cancel_requested'?'取消中':'取消任务'}</Button></Popconfirm>}</Space>}>{latestJob?<><Space wrap><Tag color={statusColor[latestJob.status]}>{statusLabel[latestJob.status]||latestJob.status}</Tag><b>#{latestJob.id}</b><span>{latestJob.current_step}</span></Space><Progress percent={latestJob.progress} status={latestJob.status==='failed'?'exception':latestJob.status==='completed'?'success':latestJob.status==='cancelled'?'normal':'active'}/><div className="factory-job-stats"><span>净化版 {latestJob.clean_count}</span><span>高能版 {latestJob.publish_count}</span><span>Meta 单集 {latestJob.meta_count}</span><span>移除 {clock(latestJob.removed_seconds)}</span><span>输出 {size(latestJob.output_bytes)}</span></div>{latestJob.warnings.length>0&&<Collapse className="factory-change-log" expandIconPosition="end" items={[{key:`job-${latestJob.id}-changes`,label:<div className="factory-change-log-title"><CheckCircleFilled/><span><b>本次自动调整 {latestJob.warnings.length} 项</b><small>点击展开查看拆分、合并与顺延记录</small></span></div>,children:<div className="factory-change-log-list">{latestJob.warnings.map((x,index)=><Alert key={`${index}-${x}`} type="success" showIcon message={x}/>)}</div>}]}/>} {latestJob.error_message&&<Alert type="error" showIcon message={latestJob.error_message}/>}</>:<Empty description="暂无加工任务"/>}</Card></div>
      <Card title="我的成品"><Table<FactoryOutputRow> rowKey={row=>row.meta_folder?`meta-folder-${row.factory_job_id}`:String(row.id)} dataSource={outputRows} pagination={{pageSize:12}} locale={{emptyText:'任务完成后会出现在这里，仅当前登录账号可见'}} columns={[{title:'类型',width:145,render:(_,row)=>row.meta_folder?<Tag color="gold">Meta 投递文件夹</Tag>:(()=>{const item=assetLabels[row.kind];return <Tag color={item.color}>{item.text}</Tag>})()},{title:'成品',render:(_,row)=>row.meta_folder?<div><b>{row.filename}</b><br/><Typography.Text type="secondary">{usingLocal?'本机已保存':'服务器已保存'} · 共 {row.meta_episode_count} 集 · 无需重复导入</Typography.Text></div>:<Typography.Text ellipsis={{tooltip:row.filename}}>{row.filename}</Typography.Text>},{title:'时长',width:105,render:(_,row)=>clock(row.duration)},{title:'大小',width:100,render:(_,row)=>size(row.size_bytes)},{title:'内容',width:140,render:(_,row)=>row.meta_folder?`${row.meta_episode_count} 集`:row.hook_asset_ids?.length?row.hook_asset_ids.map(id=>`#${id}`).join(' + '):row.hook_asset_id?`#${row.hook_asset_id}`:'—'},{title:'操作',width:440,render:(_,row)=>row.meta_folder?<Space wrap><Button icon={<EyeOutlined/>} onClick={()=>{const members=row.meta_assets??[];setMetaPreviewAssets(members);setMetaPreviewId(members[0]?.id)}}>预览文件夹</Button><Button type="primary" onClick={()=>navigate(`/meta-delivery?drama=${row.drama_id}`)}>继续 Meta 官方投递</Button></Space>:<Space wrap><Button size="small" icon={<DownloadOutlined/>} href={assetUrl(row.id)} target="_blank">打开</Button><Button size="small" icon={<CloudUploadOutlined/>} loading={clouding===row.id} disabled={usingLocal} title={usingLocal?'本机成品上传云剧库将在下一步单独确认，避免误传大文件':''} onClick={()=>uploadCloud(row)}>上传云剧库</Button><Button size="small" icon={<ExportOutlined/>} onClick={()=>handoffToJianying(row)}>剪映</Button>{row.clip_id&&!usingLocal&&<Button size="small" type="primary" icon={<RocketOutlined/>} onClick={()=>navigate(`/publishing?drama=${row.drama_id}`)}>发布</Button>}</Space>}]} scroll={{x:1090}}/></Card>
    </div>}

    {tab==='hooks'&&<div className="factory-inner"><div className="module-toolbar"><Segmented value={hookScope} onChange={v=>setHookScope(v as typeof hookScope)} options={[{value:'current',label:'当前剧目'},{value:'all',label:'全部剧目'}]}/><Space><Button icon={<ReloadOutlined/>} disabled={!dramaId} onClick={async()=>{if(dramaId)await api.syncFactoryHooks(dramaId);if(dramaId)await loadFactory(dramaId)}}>同步高能点</Button><Button type="primary" loading={busy} disabled={!dramaId} onClick={refreshHookMetrics}>刷新平台表现</Button></Space></div><Card className="table-card"><Table rowKey="id" dataSource={visibleHooks} pagination={{pageSize:12}} columns={[{title:'排名',width:70,render:(_,__,index)=>index+1},{title:'高能点',render:(_,row)=><Space direction="vertical" size={0}><b>#{row.id} · {row.drama_title}</b><Typography.Text type="secondary">{row.episode} · {clock(row.start)}–{clock(row.end)}</Typography.Text></Space>},{title:'依据',dataIndex:'note',ellipsis:true},{title:'热度',width:105,render:(_,row)=><b>{row.heat_score.toLocaleString()}</b>},{title:'发布表现',width:180,render:(_,row)=><Space size={4} wrap><Tag>播放 {row.views.toLocaleString()}</Tag><Tag>赞 {row.likes.toLocaleString()}</Tag><Tag>评 {row.comments.toLocaleString()}</Tag></Space>},{title:'复用',width:80,dataIndex:'use_count'},{title:'状态',width:90,render:(_,row)=><Switch size="small" checked={row.active} onChange={value=>toggleHook(row,value)}/>},{title:'预览',width:80,render:(_,row)=>row.preview_ready?<Button size="small" href={`/api/factory/hooks/${row.id}/video`} target="_blank">查看</Button>:'待生成'}]} scroll={{x:1000}}/></Card></div>}

    <Modal title="Meta 投递文件夹预览" open={Boolean(metaPreviewAssets.length)} onCancel={()=>{setMetaPreviewAssets([]);setMetaPreviewId(undefined)}} footer={<Button onClick={()=>{setMetaPreviewAssets([]);setMetaPreviewId(undefined)}}>关闭</Button>} width={920} destroyOnHidden><div className="meta-folder-preview"><div className="meta-folder-player">{metaPreviewId?<video controls preload="metadata" src={assetUrl(metaPreviewId)}/>:<Empty description="选择一个视频"/>}</div><Table rowKey="id" size="small" dataSource={metaPreviewAssets} pagination={{pageSize:10}} onRow={row=>({onClick:()=>setMetaPreviewId(row.id)})} rowClassName={row=>row.id===metaPreviewId?'is-active':''} columns={[{title:'集数',width:72,render:(_,row)=>`第 ${row.sequence} 集`},{title:'文件名',dataIndex:'filename',ellipsis:true},{title:'时长',width:90,render:(_,row)=>clock(row.duration)},{title:'大小',width:90,render:(_,row)=>size(row.size_bytes)},{title:'预览',width:72,render:(_,row)=><Button type="link" size="small" onClick={event=>{event.stopPropagation();setMetaPreviewId(row.id)}}>播放</Button>}]} scroll={{y:360}}/></div></Modal>
  </div>
}
