import { useEffect, useState } from 'react'
import { Button, Card, Checkbox, Form, Image, Input, InputNumber, message, Select, Space, Spin, Switch, Table, Tag, Typography } from 'antd'
import { ArrowLeftOutlined, PlusOutlined, SaveOutlined } from '@ant-design/icons'
import { useNavigate, useParams } from 'react-router-dom'
import { api, Drama, EmotionWord, Highlight, HookSuggestion } from '../api'

export default function DramaDetail(){
 const{id=''}=useParams();const navigate=useNavigate();const[drama,setDrama]=useState<Drama>();const[suggestions,setSuggestions]=useState<HookSuggestion[]>([]);const[words,setWords]=useState<EmotionWord[]>([]);const[newWord,setNewWord]=useState('');const[analyzing,setAnalyzing]=useState(false);const[loading,setLoading]=useState(true);const[form]=Form.useForm();const[msg,context]=message.useMessage()
 const load=async()=>{try{const data=await api.get(id);setDrama(data);form.setFieldsValue({...data,genres:data.genres.join('、'),actor_names:data.actor_names.join('、')})}catch(e){msg.error((e as Error).message)}finally{setLoading(false)}}
 const loadHooks=async()=>{const[s,w]=await Promise.all([api.hookSuggestions(Number(id)),api.emotionWords()]);setSuggestions(s);setWords(w)}
 useEffect(()=>{load();loadHooks().catch(e=>msg.error(e.message))},[id])
 const saveInfo=async(values:Record<string,unknown>)=>{if(!drama)return;const split=(v:unknown)=>String(v??'').split(/[、,，]/).map(x=>x.trim()).filter(Boolean);try{await api.update(drama.id,{...values,genres:split(values.genres),actor_names:split(values.actor_names)});msg.success('剧目资料已保存');await load()}catch(e){msg.error((e as Error).message)}}
 const saveHighlights=async()=>{if(!drama)return;try{setDrama(await api.highlights(drama.id,drama.highlights));msg.success('高能点已写入 highlights.json')}catch(e){msg.error((e as Error).message)}}
 const changeRow=(index:number,patch:Partial<Highlight>)=>setDrama(d=>d?({...d,highlights:d.highlights.map((x,i)=>i===index?{...x,...patch}:x)}):d)
 const analyze=async()=>{if(!drama)return;setAnalyzing(true);try{setSuggestions(await api.analyzeHooks(drama.id));msg.success('每集 Top5 建议已生成')}catch(e){msg.error((e as Error).message)}finally{setAnalyzing(false)}}
 const decide=async(item:HookSuggestion,action:'adopt'|'ignore')=>{await api.decideHook(item.id,action);await loadHooks();if(action==='adopt')await load();msg.success(action==='adopt'?'建议已采纳到高能点':'建议已忽略')}
 if(loading||!drama)return <Spin fullscreen/>
 const columns=[{title:'剧集',render:(_:unknown,r:Highlight,i:number)=><Select value={r.episode} options={drama.episodes.map(x=>({value:x}))} onChange={v=>changeRow(i,{episode:v})}/>},{title:'开始（秒）',render:(_:unknown,r:Highlight,i:number)=><InputNumber min={0} value={r.start} onChange={v=>changeRow(i,{start:v??0})}/>},{title:'结束（秒）',render:(_:unknown,r:Highlight,i:number)=><InputNumber min={0.1} value={r.end} onChange={v=>changeRow(i,{end:v??0})}/>},{title:'说明',render:(_:unknown,r:Highlight,i:number)=><Input value={r.note} onChange={e=>changeRow(i,{note:e.target.value})}/>},{title:'',render:(_:unknown,__ :Highlight,i:number)=><Button danger type="link" onClick={()=>setDrama(d=>d?({...d,highlights:d.highlights.filter((_,n)=>n!==i)}):d)}>删除</Button>}]
 const suggestionColumns=[{title:'剧集',dataIndex:'episode'},{title:'建议时间',render:(_:unknown,r:HookSuggestion)=>`${r.start}s – ${r.end}s`},{title:'依据',render:(_:unknown,r:HookSuggestion)=>r.reasons.map(x=><Tag key={x}>{x}</Tag>)},{title:'状态',dataIndex:'status'},{title:'人工决定',render:(_:unknown,r:HookSuggestion)=><Space><Button type="primary" disabled={r.status!=='pending'} onClick={()=>decide(r,'adopt')}>采纳</Button><Button disabled={r.status!=='pending'} onClick={()=>decide(r,'ignore')}>忽略</Button></Space>}]
 return <>{context}<Button icon={<ArrowLeftOutlined/>} onClick={()=>navigate('/dramas')}>返回剧库</Button><Typography.Title level={2}>{drama.title}</Typography.Title>
  <Card title="剧目资料"><Form form={form} layout="vertical" onFinish={saveInfo}><div className="form-grid"><Form.Item label="题材（顿号或逗号分隔）" name="genres"><Input/></Form.Item><Form.Item label="演员名（选填）" name="actor_names"><Input/></Form.Item><Form.Item label="素材来源" name="source_note" rules={[{required:true,whitespace:true,message:'素材来源必填'}]}><Input/></Form.Item><Form.Item name="is_ai_generated" valuePropName="checked"><Checkbox>这是 AI 生成剧</Checkbox></Form.Item></div><Button htmlType="submit" type="primary" icon={<SaveOutlined/>}>保存资料</Button></Form></Card>
  <Card title="自动钩子建议" extra={<Button type="primary" loading={analyzing} onClick={analyze}>分析整集并生成 Top5</Button>}><Space wrap>{words.map(w=><Tag key={w.id}><Switch size="small" checked={w.enabled} onChange={enabled=>api.toggleEmotionWord(w.id,enabled).then(loadHooks)}/>{w.word}</Tag>)}<Input size="small" value={newWord} onChange={e=>setNewWord(e.target.value)} placeholder="新增情绪词" style={{width:130}}/><Button size="small" onClick={()=>api.addEmotionWord(newWord).then(()=>{setNewWord('');return loadHooks()})}>添加</Button></Space><Table rowKey="id" pagination={false} dataSource={suggestions} columns={suggestionColumns}/></Card>
  <Card title="高能点标注" extra={<Space><Button icon={<PlusOutlined/>} onClick={()=>setDrama({...drama,highlights:[...drama.highlights,{episode:drama.episodes[0],start:0,end:10,note:''}]})}>新增</Button><Button type="primary" onClick={saveHighlights}>保存标注</Button></Space>}><Table rowKey={(_,i)=>String(i)} pagination={false} dataSource={drama.highlights} columns={columns}/></Card>
  <Card title={`剧照墙（${drama.stills.length}）`}><Image.PreviewGroup><div className="stills-wall">{drama.stills.map(path=>{const name=path.split('/').pop()!;return <Image key={path} width={180} height={110} src={`/api/dramas/${drama.id}/stills/${encodeURIComponent(name)}`}/>})}</div></Image.PreviewGroup></Card></>
}
