import { useEffect,useState } from 'react'
import { Button,Card,Collapse,Empty,Form,Input,message,Modal,Progress,Space,Spin,Tag,Typography,Upload } from 'antd'
import { FolderOpenOutlined,InboxOutlined,ReloadOutlined,UploadOutlined,VideoCameraOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { api,Drama,ScanLog } from '../api'

export default function DramaLibrary(){
 const[items,setItems]=useState<Drama[]>([]);const[loading,setLoading]=useState(true);const[logs,setLogs]=useState<ScanLog[]>([]);const[uploadOpen,setUploadOpen]=useState(false);const[registerOpen,setRegisterOpen]=useState(false);const[files,setFiles]=useState<File[]>([]);const[uploadProgress,setUploadProgress]=useState<Record<string,number>>({});const[uploadForm]=Form.useForm();const[registerForm]=Form.useForm();const navigate=useNavigate();const[msg,context]=message.useMessage()
 const load=async()=>{try{setItems(await api.list())}catch(e){msg.error((e as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const scan=async()=>{setLoading(true);try{const result=await api.scan();setLogs(result.logs);await load();const imported=result.logs.filter(x=>x.status==='imported').length;msg.success(`扫描完成，新登记 ${imported} 部本地剧目`)}catch(e){msg.error((e as Error).message)}finally{setLoading(false)}}
 const upload=async(values:{title:string;source_note:string})=>{if(!files.length)return msg.warning('请至少选择一个视频文件');try{for(const file of files)await api.uploadVideo(values.title,values.source_note,file,value=>setUploadProgress(old=>({...old,[file.name]:value})));msg.success('视频已导入本地素材池');setUploadOpen(false);setFiles([]);uploadForm.resetFields();await load()}catch(e){msg.error(`导入中断：${(e as Error).message}。重新选择同一文件可续传`)}}
 const register=async(values:{title:string;absolute_path:string;source_note:string})=>{try{await api.registerDrama(values.title,values.absolute_path,values.source_note);msg.success('本地文件夹登记成功');setRegisterOpen(false);registerForm.resetFields();await load()}catch(e){msg.error((e as Error).message)}}
 const logColor:Record<string,string>={imported:'green',updated:'blue',skipped:'orange',info:'default'}
 return <div className="workspace-page local-library">{context}
  <div className="page-heading page-heading-rich"><Typography.Title level={2}>剧库</Typography.Title><Space wrap><Button icon={<UploadOutlined/>} onClick={()=>setUploadOpen(true)}>导入视频文件</Button><Button icon={<FolderOpenOutlined/>} onClick={()=>setRegisterOpen(true)}>登记现有文件夹</Button><Button type="primary" icon={<ReloadOutlined/>} onClick={scan}>扫描本地素材池</Button></Space></div>
  {!!logs.length&&<Collapse className="scan-logs" items={[{key:'logs',label:`本次扫描记录（${logs.length} 条）`,children:logs.map((entry,index)=><div className="scan-log-line" key={index}><Tag color={logColor[entry.status]}>{entry.status}</Tag><code>{entry.path}</code><span>{entry.message}</span></div>)}]}/>} 
  <Spin spinning={loading}>{items.length?<div className="card-grid local-drama-grid">{items.map(item=><Card key={item.id} hoverable actions={[<Button type="link" onClick={()=>navigate(`/dramas/${item.id}`)}>资料与高能点</Button>,<Button type="link" onClick={()=>navigate(`/factory?drama=${item.id}`)}>进入内容工厂</Button>]}><Card.Meta avatar={<VideoCameraOutlined className="card-icon"/>} title={item.title} description={<Space direction="vertical"><span>{item.episode_count} 集 · {item.stills.length} 张剧照 · {item.highlights.length} 个已采纳高能点</span><span>{item.genres.map(x=><Tag key={x}>{x}</Tag>)}</span><span>来源：{item.source_note}</span><Typography.Text type="secondary" ellipsis={{tooltip:item.file_dir}}>本地：{item.file_dir}</Typography.Text></Space>}/></Card>)}</div>:!loading&&<Card className="library-empty"><Empty description="本地素材池为空；从现有后台下载剧目后，登记文件夹即可开始工作"/></Card>}</Spin>
  <Modal width={620} title="导入剧集视频到本地素材池" open={uploadOpen} onCancel={()=>setUploadOpen(false)} footer={null}><Form form={uploadForm} layout="vertical" onFinish={upload}><Form.Item name="title" label="剧名" rules={[{required:true}]}><Input placeholder="同一剧目的多集视频请填写相同剧名"/></Form.Item><Form.Item name="source_note" label="素材来源 / 授权说明" rules={[{required:true}]}><Input placeholder="记录原后台或版权来源，便于追溯"/></Form.Item><Upload.Dragger multiple accept="video/mp4,video/quicktime,video/x-matroska,video/webm" beforeUpload={()=>false} onChange={({fileList})=>setFiles(fileList.map(x=>x.originFileObj).filter(Boolean) as File[])}><p className="ant-upload-drag-icon"><InboxOutlined/></p><p className="ant-upload-text">拖入本地剧集视频，或点击选择文件</p><p className="ant-upload-hint">文件会复制到本应用的本地素材目录；支持 MP4、MOV、MKV、WebM 和断点续传</p></Upload.Dragger>{files.map(file=><div key={file.name} className="upload-file"><span>{file.name} · {(file.size/1024/1024).toFixed(1)} MB</span><Progress percent={uploadProgress[file.name]??0}/></div>)}<Button block type="primary" htmlType="submit" disabled={!files.length}>导入 {files.length||0} 个本地文件</Button></Form></Modal>
  <Modal title="登记现有本地文件夹" open={registerOpen} onCancel={()=>setRegisterOpen(false)} footer={null}><Form form={registerForm} layout="vertical" onFinish={register}><Form.Item name="title" label="剧名" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="absolute_path" label="本地绝对路径" rules={[{required:true}]}><Input placeholder="例如 D:\短剧素材\我的短剧 或 D:\短剧素材\01.mp4"/></Form.Item><Form.Item name="source_note" label="素材来源 / 授权说明" rules={[{required:true}]}><Input/></Form.Item><Button block type="primary" htmlType="submit">校验本地文件并登记</Button></Form></Modal>
 </div>
}
