import { useEffect, useState } from 'react'
import { Button, Card, Form, Input, message, Popconfirm, Select, Space, Switch, Table, Tag, Typography } from 'antd'
import { api, ContentExample, TagLibraryItem } from '../api'

const meta=(v:{genres?:string;language?:string;platform?:string})=>({genres:(v.genres??'').split(/[，,\s]+/).filter(Boolean),language:v.language||'English',platform:v.platform||'all'})
export default function Library(){
 const[examples,setExamples]=useState<ContentExample[]>([]);const[tags,setTags]=useState<TagLibraryItem[]>([]);const[msg,holder]=message.useMessage();const load=async()=>{const[e,t]=await Promise.all([api.examples(),api.tags()]);setExamples(e);setTags(t)};useEffect(()=>{load().catch(e=>msg.error(e.message))},[])
 const addExample=async(v:{content:string;genres:string;language:string;platform:string})=>{await api.createExample({...v,...meta(v),enabled:true});msg.success('样本已新增');await load()}
 const batch=async(v:{text:string;genres:string;language:string;platform:string})=>{const made=await api.batchExamples({text:v.text,...meta(v)});msg.success(`批量导入 ${made.length} 条`);await load()}
 const addTag=async(v:{tag:string;genres:string;language:string;platform:string})=>{await api.createTag({...v,...meta(v),enabled:true});msg.success('标签已新增');await load()}
 const common=(prefix:string)=><><Form.Item name="genres" label="题材"><Input placeholder="测试，情感"/></Form.Item><Form.Item name="language" label="语言" initialValue="English"><Input/></Form.Item><Form.Item name="platform" label="平台" initialValue="all"><Select options={['all','tiktok','facebook','youtube'].map(x=>({value:x,label:x}))}/></Form.Item><Button type="primary" htmlType="submit">{prefix}</Button></>
 const ecols=[{title:'样本',dataIndex:'content'},{title:'筛选标签',render:(_:unknown,r:ContentExample)=><>{r.genres.map(x=><Tag key={x}>{x}</Tag>)}<Tag>{r.language}</Tag><Tag>{r.platform}</Tag></>},{title:'启用',render:(_:unknown,r:ContentExample)=><Switch checked={r.enabled} onChange={enabled=>api.updateExample(r.id,{...r,enabled}).then(load)}/>},{title:'',render:(_:unknown,r:ContentExample)=><Popconfirm title="确认删除？" onConfirm={()=>api.deleteExample(r.id).then(load)}><Button danger>删除</Button></Popconfirm>}]
 const tcols=[{title:'标签',dataIndex:'tag'},{title:'题材/语言/平台',render:(_:unknown,r:TagLibraryItem)=><>{r.genres.map(x=><Tag key={x}>{x}</Tag>)}<Tag>{r.language}</Tag><Tag>{r.platform}</Tag></>},{title:'启用',render:(_:unknown,r:TagLibraryItem)=><Switch checked={r.enabled} onChange={enabled=>api.updateTag(r.id,{...r,enabled}).then(load)}/>},{title:'',render:(_:unknown,r:TagLibraryItem)=><Button danger onClick={()=>api.deleteTag(r.id).then(load)}>删除</Button>}]
 return <>{holder}<Typography.Title level={2}>样本库与 Tag 库</Typography.Title><div className="creative-grid"><Card title="新增爆款样本"><Form layout="vertical" onFinish={addExample}><Form.Item name="content" label="标题或文案" rules={[{required:true}]}><Input.TextArea rows={4}/></Form.Item>{common('新增样本')}</Form></Card><Card title="批量导入竞品标题"><Form layout="vertical" onFinish={batch}><Form.Item name="text" label="每行一条" rules={[{required:true}]}><Input.TextArea rows={6}/></Form.Item>{common('批量导入')}</Form></Card><Card title="新增 Tag"><Form layout="vertical" onFinish={addTag}><Form.Item name="tag" label="标签" rules={[{required:true}]}><Input placeholder="#高能反转"/></Form.Item>{common('新增标签')}</Form></Card></div><Card title={`样本（${examples.length}）`}><Table rowKey="id" dataSource={examples} columns={ecols}/></Card><Card title={`Tag（${tags.length}）`}><Table rowKey="id" dataSource={tags} columns={tcols}/></Card></>
}
