import { Alert, Button, Card, Descriptions, Form, Input, List, Popconfirm, Select, Space, Switch, Table, Tag, Typography, message } from 'antd'
import { CheckCircleOutlined, CloudUploadOutlined, LinkOutlined, SafetyCertificateOutlined, ThunderboltOutlined } from '@ant-design/icons'
import { useEffect, useState } from 'react'
import { api, type Drama, type MetaPackage, type MetaPreflight, type MetaSFSInput } from '../api'

const genres=['Action','Adventure','Animated','Comedy','Crime','Documentary','Drama','Family','Fantasy','Historical','Horror','Musical','Mystery','Noir','Reality','Romance','Science fiction','Sports','Thriller','Western']
const defaults={locale:'en_US',genres:['Drama'],release_date:new Date().toLocaleDateString('en-US',{month:'2-digit',day:'2-digit',year:'numeric'}),cast_list:'',tags:'short drama',geogating:'',ai_content:false,dubbed_content:false,include_episode_csv:true,include_thumbnails:true}

export default function MetaDelivery({embedded=false}:{embedded?:boolean}){
 const[dramas,setDramas]=useState<Drama[]>([]);const[check,setCheck]=useState<MetaPreflight>();const[packages,setPackages]=useState<MetaPackage[]>([]);const[checking,setChecking]=useState(false);const[building,setBuilding]=useState(false);const[uploading,setUploading]=useState<number|null>(null);const[msg,ctx]=message.useMessage();const[form]=Form.useForm()
 const load=async()=>{const[d,p]=await Promise.all([api.list(),api.metaPackages()]);setDramas(d);setPackages(p)};useEffect(()=>{load().catch(e=>msg.error(e.message))},[])
 const body=(v:any):MetaSFSInput=>({...v,series_slug:v.series_slug||'',cast_list:String(v.cast_list||'').split(',').map((x:string)=>x.trim()).filter(Boolean),tags:String(v.tags||'').split(',').map((x:string)=>x.trim()).filter(Boolean),geogating:String(v.geogating||'').split(',').map((x:string)=>x.trim().toUpperCase()).filter(Boolean)})
 const preflight=async()=>{try{const values=await form.validateFields();setChecking(true);const result=await api.metaPreflight(body(values));setCheck(result);if(!values.series_slug)form.setFieldValue('series_slug',result.series_slug);msg[result.ready?'success':'warning'](result.ready?'预检通过，可以构建官方投递包':`发现 ${result.blockers.length} 个阻塞项`)}catch(e){msg.error((e as Error).message)}finally{setChecking(false)}}
 const build=async()=>{try{const values=await form.validateFields();setBuilding(true);const item=await api.buildMetaPackage(body(values));msg.success('Meta SFS 投递包已构建并二次校验通过');setCheck(undefined);await load();navigator.clipboard?.writeText(item.output_dir)}catch(e){msg.error((e as Error).message)}finally{setBuilding(false)}}
 const upload=async(id:number)=>{setUploading(id);try{const item=await api.uploadMetaPackage(id);msg.success('已上传 Google Drive，并授予 Meta SFS 服务账号 Viewer 权限');await load();if(item.drive_folder_url)window.open(item.drive_folder_url,'_blank')}catch(e){msg.error((e as Error).message)}finally{setUploading(null)}}
 return <div className="workspace-page">{ctx}{embedded?<div className="module-toolbar"><b>Meta 官方投递</b><Tag icon={<SafetyCertificateOutlined/>} color="green">v260626 规范</Tag></div>:<Space className="page-heading" align="start"><Typography.Title level={2}>Meta 官方投递</Typography.Title><Tag icon={<SafetyCertificateOutlined/>} color="green">v260626 规范</Tag></Space>}
  <div className="split-workbench"><Card title="系列投递设置"><Form form={form} layout="vertical" initialValues={defaults}><Form.Item name="drama_id" label="剧目" rules={[{required:true}]}><Select options={dramas.map(x=>({value:x.id,label:`${x.title} · ${x.episode_count} 集`}))}/></Form.Item><Form.Item name="series_slug" label="系列英文标识（自动生成，可修改）" tooltip="必须是 kebab-case；所有文件会统一使用此前缀"><Input placeholder="例如 boss-like-me"/></Form.Item><Form.Item name="description" label="英文简介" rules={[{required:true}]}><Input.TextArea rows={3}/></Form.Item><div className="form-grid"><Form.Item name="locale" label="Locale" rules={[{required:true}]}><Input/></Form.Item><Form.Item name="release_date" label="首发日期 MM/DD/YYYY" rules={[{required:true}]}><Input/></Form.Item></div><Form.Item name="genres" label="Meta 官方 Genre" rules={[{required:true}]}><Select mode="multiple" options={genres.map(x=>({value:x,label:x}))}/></Form.Item><Form.Item name="cast_list" label="演员与 IG Handle（逗号分隔）"><Input placeholder="Sue Smith @suesmith, Peter Max @petermax"/></Form.Item><Form.Item name="tags" label="搜索标签（逗号分隔）"><Input/></Form.Item><Form.Item name="geogating" label="允许国家 ISO 代码（留空不限）"><Input placeholder="US, SG, IN"/></Form.Item><Space size="large" wrap><Form.Item name="ai_content" valuePropName="checked" label="AI 内容"><Switch/></Form.Item><Form.Item name="dubbed_content" valuePropName="checked" label="配音内容"><Switch/></Form.Item><Form.Item name="include_episode_csv" valuePropName="checked" label="剧集 CSV"><Switch/></Form.Item><Form.Item name="include_thumbnails" valuePropName="checked" label="自动缩略图"><Switch/></Form.Item></Space><Space wrap><Button loading={checking} icon={<SafetyCertificateOutlined/>} onClick={preflight}>执行严格预检</Button><Button type="primary" loading={building} disabled={!check?.ready} icon={<ThunderboltOutlined/>} onClick={build}>一键构建合规文件夹</Button></Space></Form></Card>
   <Card title="官方规范检查结果" className="validation-card">{!check?<div className="empty-state"><SafetyCertificateOutlined/><b>等待预检</b></div>:<><Alert type={check.ready?'success':'error'} showIcon message={check.ready?'没有阻塞项，构建时会自动修复媒体格式':'必须先处理以下阻塞项'} description={check.blockers.length?<ul>{check.blockers.map(x=><li key={x}>{x}</li>)}</ul>:'所有必需字段与源素材均可进入构建'}/><Descriptions size="small" column={1} bordered items={Object.entries(check.requirements).map(([key,value])=>({key,label:key,children:value}))}/><List size="small" header={<b>自动处理</b>} dataSource={check.automatic_fixes} renderItem={x=><List.Item><CheckCircleOutlined className="ok-icon"/> {x}</List.Item>}/><Table size="small" pagination={false} rowKey="episode" dataSource={check.assets} columns={[{title:'集',dataIndex:'episode'},{title:'目标文件名',dataIndex:'target'},{title:'源时长',render:(_,r)=>`${Number(r.info.duration||0).toFixed(1)}s`},{title:'处理',dataIndex:'issues',render:(x:string[])=><span>{x.join('；')||'直接规范化'}</span>} ]}/></>}</Card></div>
  <Card title="已生成的投递包"><Table rowKey="id" dataSource={packages} scroll={{x:1100}} columns={[{title:'系列',dataIndex:'series_slug'},{title:'状态',dataIndex:'status',render:(x:string)=><Tag color={x==='drive_ready'?'success':x==='upload_failed'?'error':x==='uploading'?'processing':'green'}>{x==='drive_ready'?'Drive 已就绪':x==='upload_failed'?'上传失败':x==='uploading'?'上传中':'本地验证通过'}</Tag>},{title:'生成时间',dataIndex:'created_at',render:(x:string)=>new Date(x).toLocaleString()},{title:'本地路径',dataIndex:'output_dir',width:320,render:(x:string)=><Typography.Text ellipsis={{tooltip:x}} copyable>{x}</Typography.Text>},{title:'Google Drive',width:210,render:(_,r)=>r.drive_folder_url?<Button type="link" href={r.drive_folder_url} target="_blank" icon={<LinkOutlined/>}>打开文件夹</Button>:<Popconfirm title="将整个投递包上传到 Google Drive，并共享给 Meta SFS 服务账号，确认继续？" onConfirm={()=>upload(r.id)}><Button loading={uploading===r.id} icon={<CloudUploadOutlined/>}>上传并授权</Button></Popconfirm>},{title:'最后提交',width:150,render:(_,r)=> <Button type="primary" href="https://www.instagram.com/sfs_tools" target="_blank" disabled={!r.drive_folder_url}>打开 SFS Tools</Button>},{title:'错误',dataIndex:'last_error',ellipsis:true,render:(x:string)=>x?<Typography.Text type="danger">{x}</Typography.Text>:'—'} ]}/></Card>
 </div>
}
