import { useEffect,useMemo,useState } from 'react'
import { Alert,Avatar,Button,Card,Drawer,Empty,Input,InputNumber,Popconfirm,Select,Segmented,Space,Spin,Table,Tag,Typography,message } from 'antd'
import { ArrowDownOutlined,ArrowUpOutlined,DownloadOutlined,EyeOutlined,FileProtectOutlined,HistoryOutlined,PlayCircleOutlined,ReloadOutlined,RiseOutlined,RocketOutlined,SearchOutlined,UserOutlined } from '@ant-design/icons'
import { useLocation,useNavigate,useParams } from 'react-router-dom'
import { api,type PromotionDrama,type RadarDrama,type RadarLive,type RadarProfile,type RadarQuota,type RadarResult,type RadarSnapshot,type RightsCase } from '../api'
import { PlatformLogo } from '../components/PlatformBrand'
import { SmoothLineChart } from '../components/SmoothLineChart'
import RadarAccounts from './RadarAccounts'

const compact=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(value)
const clock=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));const hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60),rest=value%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${minutes}:${String(rest).padStart(2,'0')}`}
const identity:Record<string,[string,string]>={own_official:['自家官方','green'],own_creator:['自家达人','green'],authorized_partner:['授权合作方','cyan'],known_distributor:['其他分销方','blue'],unknown:['未知账号','default'],blocked:['历史风险账号','red']}
const classification:Record<string,string>={own:'我方内容',authorized:'已授权',external_promotion:'外部推广',suspected_full_reupload:'疑似全集转载',suspected_episode_reupload:'疑似连续分集',suspected_impersonation:'疑似冒充官方',suspected_external_redirect:'疑似外链截流',unknown:'未分类'}
const riskValues=new Set(['suspected_full_reupload','suspected_episode_reupload','suspected_impersonation','suspected_external_redirect'])
const sourceLabel:Record<string,string>={manual_confirmed:'已有名单确认',owned_publish:'账号实际发布',external_market:'外部市场补充'}

function RadarCard({item,open,classify}:{item:RadarResult;open:()=>void;classify:(value:string)=>void}){
 const delta=item.previous_rank?item.previous_rank-item.rank:null;const meta=identity[item.relationship_type]||identity.unknown
 return <article className={`radar-result-card ${item.rank<=5?'is-leading':''}`}>
  <div className="radar-result-media" onClick={open}>{item.thumbnail_url?<img src={item.thumbnail_url} alt=""/>:<div><PlatformLogo platform="youtube" size={30}/></div>}<span className="radar-rank">#{item.rank}</span><span className="radar-play"><PlayCircleOutlined/></span></div>
  <div className="radar-result-copy"><div className="radar-result-tags"><Tag color={meta[1]}>{meta[0]}</Tag><Tag color={riskValues.has(item.classification)?'red':undefined}>{classification[item.classification]||item.classification}</Tag>{delta!=null&&delta!==0?<Tag color={delta>0?'green':'red'}>{delta>0?<ArrowUpOutlined/>:<ArrowDownOutlined/>} {Math.abs(delta)}</Tag>:null}</div><b>{item.title}</b><div className="radar-channel"><Avatar size={24} src={item.channel_avatar_url} icon={<UserOutlined/>}/><span>{item.channel_name}</span>{item.channel_subscribers!=null&&<small>{compact(item.channel_subscribers)} 订阅</small>}</div><div className="radar-metrics"><span>{compact(item.views)} 播放</span><span>{compact(item.likes)} 赞</span><span>{compact(item.comments)} 评论</span>{item.view_growth!=null&&<span className="is-growth">+{compact(item.view_growth)}</span>}<span>{clock(item.duration_seconds)}</span></div><small>{item.published_at?new Date(item.published_at).toLocaleString('zh-CN'):'发布时间未知'}</small></div>
  <div className="radar-result-actions"><Button icon={<EyeOutlined/>} onClick={open}>查看详情</Button><Select value={item.classification} onChange={classify} options={Object.entries(classification).map(([value,label])=>({value,label}))}/></div>
 </article>
}

function PromotionPoolPanel(){
 const[all,setAll]=useState<RadarDrama[]>([]);const[pool,setPool]=useState<PromotionDrama[]>([]);const[quota,setQuota]=useState<RadarQuota>();const[adding,setAdding]=useState<number>();const[msg,holder]=message.useMessage()
 const load=()=>Promise.all([api.radarDramas(true),api.promotionPool(),api.radarQuota()]).then(([dramas,rows,nextQuota])=>{setAll(dramas);setPool(rows);setQuota(nextQuota)})
 useEffect(()=>{load().catch(error=>msg.error((error as Error).message))},[])
 const add=async(id:number)=>{setAdding(id);try{await api.upsertPromotionDrama(id,{source:'manual_confirmed'});await load();msg.success('已加入推广剧目池')}catch(error){msg.error((error as Error).message)}finally{setAdding(undefined)}}
 const remove=async(id:number)=>{try{await api.removePromotionDrama(id);await load();msg.success('已停止自动监测')}catch(error){msg.error((error as Error).message)}}
 return <div className="radar-pool-panel">{holder}<div className="radar-pool-toolbar"><div><b>推广剧目池</b><small>每日只扫描池内剧目</small></div><Select showSearch optionFilterProp="label" placeholder="从已有名单确认剧目" loading={adding!=null} onChange={add} options={all.filter(item=>!pool.some(row=>row.drama_id===item.id&&row.active)).map(item=>({value:item.id,label:item.title}))}/></div>
  {quota&&<div className="radar-quota-strip"><span>今日搜索调用 <b>{quota.search_calls}/{quota.search_limit}</b></span><span>通用配额估算 <b>{quota.used_units}/{quota.unit_budget}</b></span><span>已扫描 <b>{quota.scan_count}</b> 部</span><Tag color="green">免费额度优先</Tag></div>}
  {pool.filter(row=>row.active).length?<div className="radar-pool-grid">{pool.filter(row=>row.active).map(row=><Card key={row.id} size="small"><div><b>{row.drama_title}</b><Space wrap>{row.sources.map(source=><Tag key={source}>{sourceLabel[source]||source}</Tag>)}</Space><small>{row.last_scanned_at?`上次扫描 ${new Date(row.last_scanned_at).toLocaleString('zh-CN')}`:'等待首次扫描'}</small></div><Popconfirm title="停止自动监测？" onConfirm={()=>remove(row.drama_id)}><Button size="small">移出</Button></Popconfirm></Card>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="先确认少量正在推广的剧目，不会自动扫描整个剧库"/>}
 </div>
}

function RadarSearch(){
 const{id}=useParams();const navigate=useNavigate();const[dramas,setDramas]=useState<RadarDrama[]>([]);const[dramaId,setDramaId]=useState<number>();const[profile,setProfile]=useState<RadarProfile>();const[region,setRegion]=useState('US');const[language,setLanguage]=useState('en');const[queryId,setQueryId]=useState<number>();const[snapshotId,setSnapshotId]=useState<number>();const[snapshots,setSnapshots]=useState<RadarSnapshot[]>([]);const[live,setLive]=useState<RadarLive>();const[loading,setLoading]=useState(false);const[scanning,setScanning]=useState(false);const[selected,setSelected]=useState<RadarResult>();const[details,setDetails]=useState<Record<string,unknown>>();const[episode,setEpisode]=useState('');const[start,setStart]=useState(0);const[end,setEnd]=useState(0);const[rightsOwner,setRightsOwner]=useState('');const[messageApi,context]=message.useMessage()
 useEffect(()=>{api.radarDramas().then(rows=>{setDramas(rows);const target=Number(id)||rows[0]?.id;setDramaId(target)}).catch(error=>void messageApi.error((error as Error).message))},[id,messageApi])
 useEffect(()=>{if(!dramaId)return;setLoading(true);Promise.all([api.radarProfile(dramaId),api.radarSnapshots(dramaId)]).then(([nextProfile,history])=>{setProfile(nextProfile);setSnapshots(history);const first=nextProfile.queries.find(item=>item.enabled);setRegion(first?.region||nextProfile.regions[0]||'US');setLanguage(first?.language||nextProfile.languages[0]||'en');setQueryId(current=>nextProfile.queries.some(item=>item.id===current)?current:first?.id)}).catch(error=>messageApi.error((error as Error).message)).finally(()=>setLoading(false))},[dramaId,messageApi])
 useEffect(()=>{if(!profile)return;const next=profile.queries.find(item=>item.enabled&&item.region===region&&item.language===language);if(next)setQueryId(next.id)},[region,language,profile])
 useEffect(()=>{if(!dramaId||!queryId)return;setLoading(true);api.radarLive(dramaId,queryId,snapshotId).then(setLive).catch(error=>messageApi.error((error as Error).message)).finally(()=>setLoading(false))},[dramaId,queryId,snapshotId,messageApi])
 const run=async()=>{if(!dramaId)return;setScanning(true);try{const result=await api.scanRadarDrama(dramaId);messageApi.success(`已采集 ${result.unique_video_count} 个真实视频`);setSnapshotId(undefined);setSnapshots(await api.radarSnapshots(dramaId,queryId));setLive(await api.radarLive(dramaId,queryId))}catch(error){messageApi.error((error as Error).message)}finally{setScanning(false)}}
 const open=async(item:RadarResult)=>{setSelected(item);setDetails(undefined);setEpisode('');setStart(0);setEnd(0);if(item.external_video_id)try{setDetails(await api.radarVideo(item.external_video_id))}catch(error){messageApi.error((error as Error).message)}}
 const classify=async(item:RadarResult,value:string)=>{if(!item.external_video_id)return;try{await api.classifyRadarVideo(item.external_video_id,value);setLive(current=>current?{...current,results:current.results.map(row=>row.id===item.id?{...row,classification:value,review_status:'reviewed'}:row)}:current);messageApi.success('人工分类已保存')}catch(error){messageApi.error((error as Error).message)}}
 const sendToFactory=async()=>{if(!selected?.external_video_id||!dramaId)return;try{const result=await api.sendRadarVideoToFactory(selected.external_video_id,{drama_id:dramaId,episode,source_start:start,source_end:end,opening_structure:'',reference_note:'传播雷达人工选中'});navigate(result.factory_url);messageApi.success('已发送到内容工厂，请确认后再生成')}catch(error){messageApi.error((error as Error).message)}}
 const prepareEvidence=async()=>{if(!selected?.external_video_id||!dramaId)return;try{const row=await api.createRadarCase({drama_id:dramaId,external_video_id:selected.external_video_id,rights_owner:rightsOwner,notes:'由传播雷达人工创建'});const result=await api.generateRadarEvidence(row.id);window.open(result.download_url,'_blank','noopener,noreferrer');messageApi.success('证据包已生成，仅供人工核验')}catch(error){messageApi.error((error as Error).message)}}
 const metricPoints=useMemo(()=>((details?.metrics as {captured_at:string;views:number}[]|undefined)||[]).map(item=>({label:new Date(item.captured_at).toLocaleString('zh-CN'),axisLabel:new Date(item.captured_at).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}),value:item.views})),[details])
 if(!dramas.length)return <><PromotionPoolPanel/><Alert showIcon type="info" message="推广剧目池为空" description="先从已有名单确认剧目，或在账号真实发布后由系统自动加入。"/></>
 return <>{context}<Spin spinning={loading}><div className="radar-search-toolbar"><Select value={dramaId} placeholder="选择推广剧目" showSearch optionFilterProp="label" onChange={value=>{setDramaId(value);navigate(`/radar/dramas/${value}`)}} options={dramas.map(item=>({value:item.id,label:item.title}))}/><Select value="youtube" disabled options={[{value:'youtube',label:'YouTube'}]}/><Select value={region} onChange={setRegion} options={(profile?.regions||['US']).map(value=>({value,label:value}))}/><Select value={language} onChange={setLanguage} options={(profile?.languages||['en']).map(value=>({value,label:value}))}/><Select value={queryId} placeholder="搜索词" onChange={value=>{setQueryId(value);setSnapshotId(undefined)}} options={(profile?.queries||[]).filter(item=>item.region===region&&item.language===language).map(item=>({value:item.id,label:item.query_text,disabled:!item.enabled}))}/><Select allowClear value={snapshotId} placeholder="最新快照" onChange={setSnapshotId} options={snapshots.filter(item=>!queryId||item.query_id===queryId).map(item=>({value:item.id,label:new Date(item.captured_at).toLocaleString('zh-CN')}))}/><Button icon={<HistoryOutlined/>} onClick={()=>setSnapshotId(snapshots.find(item=>item.query_id===queryId)?.id)}>历史</Button><Button type="primary" icon={<ReloadOutlined/>} loading={scanning} onClick={run}>立即刷新</Button></div>
  {profile?.last_error&&<Alert showIcon type="error" message="最近一次采集失败" description={profile.last_error}/>} {live?.snapshot?<><div className="radar-summary-grid">{[{label:'前 10 我方',value:live.summary.own},{label:'前 10 授权方',value:live.summary.authorized},{label:'前 10 未知账号',value:live.summary.unknown},{label:'人工风险分类',value:live.summary.risk},{label:'第一名归属',value:identity[live.summary.first_owner]?.[0]||'未知'}].map(item=><Card key={item.label}><span>{item.label}</span><b>{item.value}</b></Card>)}</div><div className="radar-context"><Space wrap><Tag><PlatformLogo platform="youtube" size={14}/> YouTube</Tag><Tag>{live.query?.region}</Tag><Tag>{live.query?.language}</Tag><Tag>{new Date(live.snapshot.captured_at).toLocaleString('zh-CN')}</Tag></Space><span>{live.standard_notice}</span></div><div className="radar-result-grid">{live.results.map(item=><RadarCard key={item.id} item={item} open={()=>open(item)} classify={value=>classify(item,value)}/>)}</div></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="尚无真实搜索快照"><Button type="primary" loading={scanning} onClick={run}>采集首轮结果</Button></Empty>}</Spin>
  <Drawer width={720} open={Boolean(selected)} onClose={()=>setSelected(undefined)} title="外部视频详情">{selected&&<div className="radar-video-drawer"><div className="radar-embed"><iframe src={selected.embed_url} title={selected.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><Typography.Title level={4}>{selected.title}</Typography.Title><Space wrap><Tag>{identity[selected.relationship_type]?.[0]||'未知账号'}</Tag><Tag color={riskValues.has(selected.classification)?'red':undefined}>{classification[selected.classification]}</Tag><Tag>标准监测第 {selected.rank} 位</Tag></Space><Typography.Paragraph ellipsis={{rows:4,expandable:true,symbol:'展开'}}>{selected.description}</Typography.Paragraph><Space wrap><Button href={selected.video_url} target="_blank">打开 YouTube</Button>{dramaId&&<Button onClick={()=>api.upsertPromotionDrama(dramaId,{source:'external_market',external_video_id:selected.external_video_id}).then(()=>messageApi.success('已记录外部市场来源')).catch(error=>messageApi.error((error as Error).message))}>记录外部市场来源</Button>}</Space><Card title="播放增长" className="radar-drawer-chart"><SmoothLineChart points={metricPoints} seriesName="播放量" valueFormat={compact} ariaLabel="播放增长曲线" emptyText="需要至少两次快照才能显示增长"/></Card><Card title="发送到内容工厂"><div className="radar-handoff-fields"><Input value={episode} onChange={event=>setEpisode(event.target.value)} placeholder="对应集数，例如 Episode12"/><InputNumber min={0} value={start} onChange={value=>setStart(value||0)} addonAfter="开始秒"/><InputNumber min={0} value={end} onChange={value=>setEnd(value||0)} addonAfter="结束秒"/><Button type="primary" icon={<RocketOutlined/>} onClick={sendToFactory}>预填并前往确认</Button></div></Card>{riskValues.has(selected.classification)&&<Card title="人工证据"><div className="radar-evidence-fields"><Input value={rightsOwner} onChange={event=>setRightsOwner(event.target.value)} placeholder="权利主体（人工填写）"/><Button icon={<FileProtectOutlined/>} onClick={prepareEvidence}>生成证据包</Button></div></Card>}</div>}</Drawer></>
}

function TodayEvents(){const[events,setEvents]=useState<Awaited<ReturnType<typeof api.radarEvents>>>([]);const navigate=useNavigate();useEffect(()=>{api.radarEvents(10).then(setEvents)},[]);return <><PromotionPoolPanel/>{events.length?<div className="radar-events-list">{events.map(item=><Card key={item.id} onClick={()=>navigate(`/radar/dramas/${item.drama_id}`)}><div className="radar-event-thumb">{item.thumbnail_url?<img src={item.thumbnail_url} alt=""/>:<RiseOutlined/>}</div><div><Space><Tag color={item.severity==='high'?'red':item.severity==='positive'?'green':'cyan'}>{item.severity==='high'?'风险':item.severity==='positive'?'占位':'机会'}</Tag><b>{item.drama_title}</b></Space><strong>{item.title}</strong><span>{item.summary}</span></div><Button>查看现场</Button></Card>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="每日扫描后，最多展示 10 条重要变化"/>}</>}

function RadarCases(){const[rows,setRows]=useState<RightsCase[]>([]);const[busy,setBusy]=useState<number>();const[msg,holder]=message.useMessage();const load=()=>api.radarCases().then(setRows);useEffect(()=>{load().catch(error=>msg.error((error as Error).message))},[]);const generate=async(row:RightsCase)=>{setBusy(row.id);try{const result=await api.generateRadarEvidence(row.id);await load();window.open(result.download_url,'_blank','noopener,noreferrer')}catch(error){msg.error((error as Error).message)}finally{setBusy(undefined)}};return <Card title="疑似侵权人工核验">{holder}<Table rowKey="id" dataSource={rows} locale={{emptyText:'在搜索现场人工分类后可创建证据记录'}} columns={[{title:'剧目',dataIndex:'drama_title'},{title:'视频',render:(_,row)=><a href={row.video_url} target="_blank" rel="noreferrer">{row.video_title}</a>},{title:'账号',dataIndex:'channel_name'},{title:'分类',render:(_,row)=><Tag color="red">{classification[row.classification]||row.classification}</Tag>},{title:'状态',dataIndex:'case_status'},{title:'操作',render:(_,row)=><Space><Button size="small" icon={<FileProtectOutlined/>} loading={busy===row.id} onClick={()=>generate(row)}>生成证据</Button>{row.evidence_ready&&<Button size="small" icon={<DownloadOutlined/>} href={`/api/radar/cases/${row.id}/download`} target="_blank">下载</Button>}</Space>}]} scroll={{x:900}}/></Card>}

export default function Radar(){
 const location=useLocation();const navigate=useNavigate();const view=location.pathname.includes('/accounts')?'accounts':location.pathname.includes('/cases')?'cases':location.pathname.includes('/dramas/')?'search':'today'
 return <div className="workspace-page radar-page"><div className="page-heading"><div><Typography.Title level={2}>传播雷达</Typography.Title><span>YouTube 标准搜索现场</span></div><Segmented value={view} onChange={value=>navigate(value==='today'?'/radar':value==='search'?'/radar/dramas/0':`/radar/${value}`)} options={[{value:'today',label:'今日动态'},{value:'search',label:'搜索现场',icon:<SearchOutlined/>},{value:'accounts',label:'监测账号'},{value:'cases',label:'疑似侵权'}]}/></div>{view==='accounts'?<RadarAccounts/>:view==='cases'?<RadarCases/>:view==='search'?<RadarSearch/>:<TodayEvents/>}</div>
}
