import { useEffect,useMemo,useState } from 'react'
import { Alert,Avatar,Button,Card,Drawer,Empty,Input,InputNumber,Select,Segmented,Space,Spin,Table,Tag,Typography,message } from 'antd'
import { ArrowDownOutlined,ArrowUpOutlined,BarChartOutlined,CalendarOutlined,CommentOutlined,DownloadOutlined,EyeOutlined,FileProtectOutlined,FireOutlined,GlobalOutlined,HistoryOutlined,PlayCircleOutlined,ReloadOutlined,RiseOutlined,RocketOutlined,SearchOutlined,TeamOutlined,TrophyOutlined,UserAddOutlined,UserOutlined } from '@ant-design/icons'
import { useLocation,useNavigate,useParams } from 'react-router-dom'
import { api,type PlatformBriefing,type RadarDrama,type RadarLive,type RadarProfile,type RadarResult,type RadarSnapshot,type RightsCase } from '../api'
import { PlatformLogo } from '../components/PlatformBrand'
import { SmoothLineChart } from '../components/SmoothLineChart'
import RadarAccounts from './RadarAccounts'

const compact=(value:number|null|undefined)=>value==null?'—':new Intl.NumberFormat('zh-CN',{notation:'compact',maximumFractionDigits:1}).format(value)
const clock=(seconds:number)=>{const value=Math.max(0,Math.round(seconds));const hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60),rest=value%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${minutes}:${String(rest).padStart(2,'0')}`}
const identity:Record<string,[string,string]>={own_official:['官方引流','green'],own_creator:['达人','green'],authorized_partner:['授权合作方','cyan'],known_distributor:['其他分销方','blue'],unknown:['未知账号','default'],blocked:['历史风险账号','red']}
const classification:Record<string,string>={own:'我方内容',authorized:'已授权',external_promotion:'外部推广',suspected_full_reupload:'疑似完整剧转载',suspected_compilation_reupload:'疑似重复/片段拼接',full_verification_pending:'待内容核验',suspected_episode_reupload:'疑似连续分集',suspected_impersonation:'疑似冒充官方',suspected_external_redirect:'疑似外链截流',unknown:'未分类'}
const riskValues=new Set(['suspected_full_reupload','suspected_compilation_reupload','suspected_episode_reupload','suspected_impersonation','suspected_external_redirect'])
const contentStructures:Record<string,[string,string]>={true_full_series:['连续完整剧结构','red'],repeated_compilation:['重复循环拼接','orange'],fragment_compilation:['片段混剪拼接','orange'],single_excerpt:['单一节选','blue'],uncertain:['待人工确认','gold'],not_analyzed:['未做内容核验','default']}
type RadarFilter='all'|'own'|'authorized'|'unknown'|'risk'|'first'

function RadarCard({item,open,classify}:{item:RadarResult;open:()=>void;classify:(value:string)=>void}){
 const delta=item.previous_rank?item.previous_rank-item.rank:null;const meta=identity[item.relationship_type]||identity.unknown
 return <article className={`radar-result-card ${item.rank<=5?'is-leading':''}`}>
  <div className="radar-result-media" onClick={open}>{item.thumbnail_url?<img src={item.thumbnail_url} alt=""/>:<div><PlatformLogo platform="youtube" size={30}/></div>}<span className="radar-rank">#{item.rank}</span><span className="radar-play"><PlayCircleOutlined/></span></div>
  <div className="radar-result-copy"><div className="radar-result-tags"><Tag color={meta[1]}>{meta[0]}</Tag><Tag color={riskValues.has(item.classification)?'red':undefined}>{classification[item.classification]||item.classification}</Tag>{item.content_structure&&item.content_structure!=='not_analyzed'&&<Tag color={contentStructures[item.content_structure]?.[1]}>{contentStructures[item.content_structure]?.[0]||item.content_structure}</Tag>}{delta!=null&&delta!==0?<Tag color={delta>0?'green':'red'}>{delta>0?<ArrowUpOutlined/>:<ArrowDownOutlined/>} {Math.abs(delta)}</Tag>:null}</div><b>{item.title}</b><div className="radar-channel"><Avatar size={24} src={item.channel_avatar_url} icon={<UserOutlined/>}/><span>{item.channel_name}</span>{item.channel_subscribers!=null&&<small>{compact(item.channel_subscribers)} 订阅</small>}</div><div className="radar-metrics"><span>{compact(item.views)} 播放</span><span>{compact(item.likes)} 赞</span><span>{compact(item.comments)} 评论</span>{item.view_growth!=null&&<span className="is-growth">+{compact(item.view_growth)}</span>}<span>{clock(item.duration_seconds)}</span></div><small>{item.published_at?new Date(item.published_at).toLocaleString('zh-CN'):'发布时间未知'}</small></div>
  <div className="radar-result-actions"><Button icon={<EyeOutlined/>} onClick={open}>查看详情</Button><Select value={item.classification} onChange={classify} options={Object.entries(classification).map(([value,label])=>({value,label}))}/></div>
 </article>
}

function RadarSearch(){
 const{id}=useParams();const navigate=useNavigate();const[dramas,setDramas]=useState<RadarDrama[]>([]);const[dramaId,setDramaId]=useState<number>();const[profile,setProfile]=useState<RadarProfile>();const[region,setRegion]=useState('US');const[language,setLanguage]=useState('en');const[queryId,setQueryId]=useState<number>();const[snapshotId,setSnapshotId]=useState<number>();const[snapshots,setSnapshots]=useState<RadarSnapshot[]>([]);const[live,setLive]=useState<RadarLive>();const[resultFilter,setResultFilter]=useState<RadarFilter>('all');const[loading,setLoading]=useState(false);const[scanning,setScanning]=useState(false);const[selected,setSelected]=useState<RadarResult>();const[details,setDetails]=useState<Record<string,unknown>>();const[episode,setEpisode]=useState('');const[start,setStart]=useState(0);const[end,setEnd]=useState(0);const[rightsOwner,setRightsOwner]=useState('');const[messageApi,context]=message.useMessage()
 useEffect(()=>{api.radarDramas().then(rows=>{setDramas(rows);const target=Number(id)||rows[0]?.id;setDramaId(target)}).catch(error=>void messageApi.error((error as Error).message))},[id,messageApi])
 useEffect(()=>{if(!dramaId)return;setLoading(true);Promise.all([api.radarProfile(dramaId),api.radarSnapshots(dramaId)]).then(([nextProfile,history])=>{setProfile(nextProfile);setSnapshots(history);const first=nextProfile.queries.find(item=>item.enabled);setRegion(first?.region||nextProfile.regions[0]||'US');setLanguage(first?.language||nextProfile.languages[0]||'en');setQueryId(current=>nextProfile.queries.some(item=>item.id===current)?current:first?.id)}).catch(error=>messageApi.error((error as Error).message)).finally(()=>setLoading(false))},[dramaId,messageApi])
 useEffect(()=>{if(!profile)return;const next=profile.queries.find(item=>item.enabled&&item.region===region&&item.language===language);if(next)setQueryId(next.id)},[region,language,profile])
 useEffect(()=>{if(!dramaId||!queryId)return;setLoading(true);api.radarLive(dramaId,queryId,snapshotId).then(setLive).catch(error=>messageApi.error((error as Error).message)).finally(()=>setLoading(false))},[dramaId,queryId,snapshotId,messageApi])
 useEffect(()=>setResultFilter('all'),[dramaId,queryId,snapshotId])
 const run=async()=>{if(!dramaId)return;setScanning(true);try{const result=await api.scanRadarDrama(dramaId);messageApi.success(`已采集 ${result.unique_video_count} 个真实视频`);setSnapshotId(undefined);setSnapshots(await api.radarSnapshots(dramaId,queryId));setLive(await api.radarLive(dramaId,queryId))}catch(error){messageApi.error((error as Error).message)}finally{setScanning(false)}}
 const open=async(item:RadarResult)=>{setSelected(item);setDetails(undefined);setEpisode('');setStart(0);setEnd(0);if(item.external_video_id)try{setDetails(await api.radarVideo(item.external_video_id))}catch(error){messageApi.error((error as Error).message)}}
 const classify=async(item:RadarResult,value:string)=>{if(!item.external_video_id)return;try{await api.classifyRadarVideo(item.external_video_id,value);setLive(current=>current?{...current,results:current.results.map(row=>row.id===item.id?{...row,classification:value,review_status:'reviewed'}:row)}:current);messageApi.success('人工分类已保存，仅对当前视频生效')}catch(error){messageApi.error((error as Error).message)}}
 const sendToFactory=async()=>{if(!selected?.external_video_id||!dramaId)return;try{const result=await api.sendRadarVideoToFactory(selected.external_video_id,{drama_id:dramaId,episode,source_start:start,source_end:end,opening_structure:'',reference_note:'平台动态人工选中'});navigate(result.factory_url);messageApi.success('已发送到内容工厂，请确认后再生成')}catch(error){messageApi.error((error as Error).message)}}
 const prepareEvidence=async()=>{if(!selected?.external_video_id||!dramaId)return;try{const row=await api.createRadarCase({drama_id:dramaId,external_video_id:selected.external_video_id,rights_owner:rightsOwner,notes:'由平台动态人工创建'});const result=await api.generateRadarEvidence(row.id);window.open(result.download_url,'_blank','noopener,noreferrer');messageApi.success('证据包已生成，仅供人工核验')}catch(error){messageApi.error((error as Error).message)}}
 const metricPoints=useMemo(()=>((details?.metrics as {captured_at:string;views:number}[]|undefined)||[]).map(item=>({label:new Date(item.captured_at).toLocaleString('zh-CN'),axisLabel:new Date(item.captured_at).toLocaleDateString('zh-CN',{month:'numeric',day:'numeric'}),value:item.views})),[details])
 const filteredResults=useMemo(()=>{const rows=live?.results||[];if(resultFilter==='all')return rows;if(resultFilter==='own')return rows.filter(item=>['own_official','own_creator'].includes(item.relationship_type));if(resultFilter==='authorized')return rows.filter(item=>!['own_official','own_creator'].includes(item.relationship_type)&&item.authorization_status==='authorized');if(resultFilter==='unknown')return rows.filter(item=>!['own_official','own_creator'].includes(item.relationship_type)&&item.authorization_status!=='authorized');if(resultFilter==='risk')return rows.filter(item=>riskValues.has(item.classification));return rows.filter(item=>item.relationship_type===live?.summary.first_owner)},[live,resultFilter])
 const filterLabels:Record<RadarFilter,string>={all:'全部结果',own:'我方账号',authorized:'授权方',unknown:'未知账号',risk:'人工风险分类',first:'第一名同类账号'}
 if(!dramas.length)return <Alert showIcon type="info" message="推广剧目池为空" description="先在剧库中选择正在推广的剧目。" action={<Button onClick={()=>navigate('/dramas')}>前往剧库</Button>}/>
 return <>{context}<Spin spinning={loading}><div className="radar-search-toolbar"><Select value={dramaId} placeholder="选择推广剧目" showSearch optionFilterProp="label" onChange={value=>{setDramaId(value);navigate(`/radar/dramas/${value}`)}} options={dramas.map(item=>({value:item.id,label:item.title}))}/><Select value="youtube" disabled options={[{value:'youtube',label:'YouTube'}]}/><Select value={region} onChange={setRegion} options={(profile?.regions||['US']).map(value=>({value,label:value}))}/><Select value={language} onChange={setLanguage} options={(profile?.languages||['en']).map(value=>({value,label:value}))}/><Select value={queryId} placeholder="搜索词" onChange={value=>{setQueryId(value);setSnapshotId(undefined)}} options={(profile?.queries||[]).filter(item=>item.region===region&&item.language===language).map(item=>({value:item.id,label:item.query_text,disabled:!item.enabled}))}/><Select allowClear value={snapshotId} placeholder="最新快照" onChange={setSnapshotId} options={snapshots.filter(item=>!queryId||item.query_id===queryId).map(item=>({value:item.id,label:new Date(item.captured_at).toLocaleString('zh-CN')}))}/><Button icon={<HistoryOutlined/>} onClick={()=>setSnapshotId(snapshots.find(item=>item.query_id===queryId)?.id)}>历史</Button><Button type="primary" icon={<ReloadOutlined/>} loading={scanning} onClick={run}>立即刷新</Button></div>
  {profile?.last_error&&<Alert showIcon type="error" message="最近一次采集失败" description={profile.last_error}/>} {live?.snapshot?<><div className="radar-summary-grid">{[{filter:'own' as RadarFilter,label:'前 10 我方',value:live.summary.own},{filter:'authorized' as RadarFilter,label:'前 10 授权方',value:live.summary.authorized},{filter:'unknown' as RadarFilter,label:'前 10 未知账号',value:live.summary.unknown},{filter:'risk' as RadarFilter,label:'人工风险分类',value:live.summary.risk},{filter:'first' as RadarFilter,label:'第一名归属',value:identity[live.summary.first_owner]?.[0]||'未知'}].map(item=>{const active=resultFilter===item.filter;const toggle=()=>setResultFilter(active?'all':item.filter);return <Card key={item.label} className={active?'is-active':''} role="button" tabIndex={0} aria-pressed={active} onClick={toggle} onKeyDown={event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle()}}}><span>{item.label}</span><b>{item.value}</b></Card>})}</div><div className="radar-context"><Space wrap><Tag><PlatformLogo platform="youtube" size={14}/> YouTube</Tag><Tag>{live.query?.region}</Tag><Tag>{live.query?.language}</Tag><Tag>{new Date(live.snapshot.captured_at).toLocaleString('zh-CN')}</Tag>{resultFilter!=='all'&&<Tag color="green" closable onClose={()=>setResultFilter('all')}>{filterLabels[resultFilter]} · {filteredResults.length}</Tag>}</Space><span>{live.standard_notice}</span></div>{filteredResults.length?<div className="radar-result-grid">{filteredResults.map(item=><RadarCard key={item.id} item={item} open={()=>open(item)} classify={value=>classify(item,value)}/>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="当前筛选下没有内容"/>}</>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="尚无真实搜索快照"><Button type="primary" loading={scanning} onClick={run}>采集首轮结果</Button></Empty>}</Spin>
  <Drawer width={720} open={Boolean(selected)} onClose={()=>setSelected(undefined)} title="外部视频详情">{selected&&<div className="radar-video-drawer"><div className="radar-embed"><iframe src={selected.embed_url} title={selected.title} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div><Typography.Title level={4}>{selected.title}</Typography.Title><Space wrap><Tag>{identity[selected.relationship_type]?.[0]||'未知账号'}</Tag><Tag color={riskValues.has(selected.classification)?'red':undefined}>{classification[selected.classification]}</Tag><Tag>标准监测第 {selected.rank} 位</Tag></Space><Typography.Paragraph ellipsis={{rows:4,expandable:true,symbol:'展开'}}>{selected.description}</Typography.Paragraph>{selected.content_structure&&selected.content_structure!=='not_analyzed'&&<Card title="内容结构核验"><Space direction="vertical" size={8}><Space wrap><Tag color={contentStructures[selected.content_structure]?.[1]}>{contentStructures[selected.content_structure]?.[0]}</Tag><Tag>置信度 {Math.round(selected.content_structure_confidence*100)}%</Tag><Tag>连续剧情 {Math.round(selected.continuous_story_ratio*100)}%</Tag><Tag>重复内容 {Math.round(selected.repetition_ratio*100)}%</Tag></Space><Typography.Text>{selected.content_structure_reason}</Typography.Text>{(selected.content_structure_evidence?.sequence||[]).map(item=><Typography.Text key={`sequence-${item}`} type="secondary">连续证据：{item}</Typography.Text>)}{(selected.content_structure_evidence?.repetition||[]).map(item=><Typography.Text key={`repeat-${item}`} type="warning">重复证据：{item}</Typography.Text>)}<Typography.Text type="secondary">该结果只判断内容结构，不直接作侵权结论。</Typography.Text></Space></Card>}<Space wrap><Button href={selected.video_url} target="_blank">打开 YouTube</Button>{dramaId&&<Button onClick={()=>api.upsertPromotionDrama(dramaId,{source:'external_market',external_video_id:selected.external_video_id}).then(()=>messageApi.success('已记录外部市场来源')).catch(error=>messageApi.error((error as Error).message))}>记录外部市场来源</Button>}</Space><Card title="播放增长" className="radar-drawer-chart"><SmoothLineChart points={metricPoints} seriesName="播放量" valueFormat={compact} ariaLabel="播放增长曲线" emptyText="需要至少两次快照才能显示增长"/></Card><Card title="发送到内容工厂"><div className="radar-handoff-fields"><Input value={episode} onChange={event=>setEpisode(event.target.value)} placeholder="对应集数，例如 Episode12"/><InputNumber min={0} value={start} onChange={value=>setStart(value||0)} addonAfter="开始秒"/><InputNumber min={0} value={end} onChange={value=>setEnd(value||0)} addonAfter="结束秒"/><Button type="primary" icon={<RocketOutlined/>} onClick={sendToFactory}>预填并前往确认</Button></div></Card>{riskValues.has(selected.classification)&&<Card title="人工证据"><div className="radar-evidence-fields"><Input value={rightsOwner} onChange={event=>setRightsOwner(event.target.value)} placeholder="权利主体（人工填写）"/><Button icon={<FileProtectOutlined/>} onClick={prepareEvidence}>生成证据包</Button></div></Card>}</div>}</Drawer></>
}

function TodayEvents(){
 const[data,setData]=useState<PlatformBriefing>();const[loading,setLoading]=useState(true);const[messageApi,holder]=message.useMessage();const navigate=useNavigate()
 const load=async(refresh=false)=>{setLoading(true);try{setData(await api.platformBriefing(refresh));if(refresh)messageApi.success('运营简报已刷新')}catch(error){messageApi.error((error as Error).message)}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 if(!data&&loading)return <div className="radar-briefing-loading"><Spin/><span>正在汇总平台数据</span></div>
 const fastest=data?.fastest_growth;const yesterday=data?.yesterday;const week=data?.week;const engagement=week?.engagement_leader;const subscriber=week?.subscriber_leader;const trafficRows=data?.traffic_sources||[];const requests=data?.full_episode_requests.items||[]
 return <div className="radar-today">{holder}<div className="radar-briefing-head"><div><Typography.Title level={3}>今日运营简报</Typography.Title><span>{data?new Date(data.generated_at).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'}):''}</span></div><Button icon={<ReloadOutlined/>} loading={loading} onClick={()=>load(true)}>刷新数据</Button></div><div className="radar-briefing-grid">
  <Card className="radar-briefing-card is-growth is-feature"><div className="radar-briefing-label"><FireOutlined/><span>{fastest?.metric_label||'播放增速最快'}</span><Tag color="green">主推</Tag></div>{fastest?<><a className="radar-feature-media" href={fastest.url} target="_blank" rel="noreferrer">{fastest.thumbnail_url?<img src={fastest.thumbnail_url} alt=""/>:<span><RiseOutlined/></span>}<div><small>{fastest.account_name}</small><h3>{fastest.title}</h3></div></a><div className="radar-feature-value"><strong>{compact(fastest.views_per_hour)}</strong><span>播放 / 小时</span></div><div className="radar-feature-kpis"><span><b>{compact(fastest.views)}</b>累计播放</span><span><b>{compact(fastest.likes)}</b>点赞</span><span><b>{compact(fastest.comments)}</b>评论</span></div></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="近 7 日暂无新视频"/>}</Card>
  <Card className="radar-briefing-card is-yesterday"><div className="radar-briefing-label"><CalendarOutlined/><span>昨天发布表现</span><Tag>{yesterday?.date.slice(5)||''}</Tag></div>{yesterday?.publish_count?<><div className="radar-inline-number"><strong>{yesterday.publish_count}</strong><span>条视频</span></div><div className="radar-briefing-kpis"><span><b>{compact(yesterday.views)}</b>播放</span><span><b>{compact(yesterday.likes)}</b>点赞</span><span><b>{compact(yesterday.comments)}</b>评论</span></div><div className="radar-briefing-mini-list">{yesterday.items.slice(0,2).map(item=><a key={`${item.account_id}-${item.video_id}`} href={item.url} target="_blank" rel="noreferrer"><span>{item.title}</span><b>{compact(item.views)}</b></a>)}</div></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="昨天没有发布内容"/>}</Card>
  <Card className="radar-briefing-card is-coverage"><div className="radar-briefing-label"><TeamOutlined/><span>账号数据覆盖</span></div><div className="radar-inline-number"><strong>{data?.coverage.connected_accounts||0}</strong><span>个已连接账号</span></div><div className="radar-coverage-state"><b>{data?.coverage.media_count||0}</b><span>条视频已汇总</span></div><Tag color={data?.coverage.errors.length?'orange':'green'}>{data?.coverage.errors.length?`${data.coverage.errors.length} 个账号需检查`:'数据连接正常'}</Tag></Card>
  <Card className="radar-briefing-card is-week"><div className="radar-briefing-label"><BarChartOutlined/><span>近 7 日新发内容</span></div><div className="radar-week-grid"><span><b>{week?.publish_count||0}</b>发布</span><span><b>{compact(week?.views)}</b>播放</span><span><b>{compact(week?.average_views)}</b>条均播放</span><span><b>{week?.engagement_rate||0}%</b>互动率</span></div><div className="radar-briefing-meta"><span>{week?.active_accounts||0} 个账号有新内容</span><span>{compact(week?.comments)} 条评论</span></div></Card>
  <Card className="radar-briefing-card is-engagement"><div className="radar-briefing-label"><TrophyOutlined/><span>互动效率最高</span></div>{engagement?<><strong>{engagement.engagement_rate}%</strong><a href={engagement.url} target="_blank" rel="noreferrer">{engagement.title}</a><div className="radar-briefing-meta"><span>{engagement.account_name}</span><span>{compact(engagement.views)} 播放</span></div></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无互动数据"/>}</Card>
  <Card className="radar-briefing-card is-traffic"><div className="radar-briefing-label"><GlobalOutlined/><span>流量来源 Top 3</span></div>{trafficRows.length?<div className="radar-traffic-list">{trafficRows.map((item,index)=><div key={item.source}><span><b>{index+1}. {item.label}</b><em>{item.share}%</em></span><i><u style={{width:`${item.share}%`}}/></i><small>{compact(item.views)} 播放</small></div>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂未取得流量来源"/>}</Card>
  <Card className="radar-briefing-card is-comment"><div className="radar-briefing-label"><CommentOutlined/><span>观众在找全集</span><Tag color={data?.full_episode_requests.count?'green':undefined}>{data?.full_episode_requests.count||0} 条</Tag></div>{requests.length?<div className="radar-comment-list">{requests.slice(0,2).map(item=><a key={item.id} href={item.video_url||undefined} target="_blank" rel="noreferrer"><blockquote>“{item.text}”</blockquote><span>{item.author_name} · {item.account_name||item.platform}</span></a>)}</div>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无全集诉求"/>}</Card>
  <Card className="radar-briefing-card is-subscriber"><div className="radar-briefing-label"><UserAddOutlined/><span>订阅转化最好</span></div>{subscriber?<><strong>+{compact(subscriber.subscribers_gained)}</strong><a href={subscriber.url} target="_blank" rel="noreferrer">{subscriber.title}</a><div className="radar-briefing-meta"><span>{subscriber.account_name}</span><span>{compact(subscriber.views)} 播放</span></div></>:<Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂未取得单视频订阅数据"/>}</Card>
 </div><section className="radar-action-strip"><div><b>必须处理</b><span>{data?.alerts.length?`${data.alerts.length} 条异常需要确认`:'暂无必须处理事项'}</span></div>{data?.alerts.length?<div>{data.alerts.map(item=><button key={item.id} onClick={()=>navigate(`/radar/dramas/${item.drama_id}`)}><Tag color="red">异常</Tag><span>{item.drama_title}</span><b>{item.title}</b></button>)}</div>:<Tag color="green">正常</Tag>}</section></div>
}

function RadarCases(){const[rows,setRows]=useState<RightsCase[]>([]);const[busy,setBusy]=useState<number>();const[msg,holder]=message.useMessage();const load=()=>api.radarCases().then(setRows);useEffect(()=>{load().catch(error=>msg.error((error as Error).message))},[]);const generate=async(row:RightsCase)=>{setBusy(row.id);try{const result=await api.generateRadarEvidence(row.id);await load();window.open(result.download_url,'_blank','noopener,noreferrer')}catch(error){msg.error((error as Error).message)}finally{setBusy(undefined)}};return <Card title="疑似侵权人工核验">{holder}<Table rowKey="id" dataSource={rows} locale={{emptyText:'在搜索现场人工分类后可创建证据记录'}} columns={[{title:'剧目',dataIndex:'drama_title'},{title:'视频',render:(_,row)=><a href={row.video_url} target="_blank" rel="noreferrer">{row.video_title}</a>},{title:'账号',dataIndex:'channel_name'},{title:'分类',render:(_,row)=><Tag color="red">{classification[row.classification]||row.classification}</Tag>},{title:'状态',dataIndex:'case_status'},{title:'操作',render:(_,row)=><Space><Button size="small" icon={<FileProtectOutlined/>} loading={busy===row.id} onClick={()=>generate(row)}>生成证据</Button>{row.evidence_ready&&<Button size="small" icon={<DownloadOutlined/>} href={`/api/radar/cases/${row.id}/download`} target="_blank">下载</Button>}</Space>}]} scroll={{x:900}}/></Card>}

export default function Radar(){
 const location=useLocation();const navigate=useNavigate();const view=location.pathname.includes('/accounts')?'accounts':location.pathname.includes('/cases')?'cases':location.pathname.includes('/dramas/')?'search':'today'
 return <div className="workspace-page radar-page"><div className="page-heading"><Space size={8}><Typography.Title level={2}>平台动态</Typography.Title><Tag color="green">团队共享</Tag></Space><Segmented value={view} onChange={value=>navigate(value==='today'?'/radar':value==='search'?'/radar/dramas/0':`/radar/${value}`)} options={[{value:'today',label:'运营简报'},{value:'search',label:'搜索现场',icon:<SearchOutlined/>},{value:'accounts',label:'监测账号'},{value:'cases',label:'疑似侵权'}]}/></div>{view==='accounts'?<RadarAccounts/>:view==='cases'?<RadarCases/>:view==='search'?<RadarSearch/>:<TodayEvents/>}</div>
}
